### ISSUE TITLE
scRNA_parse: main.c:242: parse_options: Assertion `n1==n2 && n1>0' failed.

### ISSUE THREAD

**Issue by youwh1996** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#1]
I  process the raw data and meet this problem
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/72308025/163995207-7c07847e-5182-4de9-b70c-46f54e384242.png">

**Comment by lishuangshuang0616** [comment]
Multiple fastq.gz are separated by comma, example A1_oligo_R1.gz,A2_oligo_R1.gz. There cannot be a space after a comma.
![1650425147(1)](https://user-images.githubusercontent.com/49019821/164144328-d6f16a09-9b13-4924-8b8d-d89b836b3b18.jpg)

**Comment by lishuangshuang0616** [comment]
Multiple fastq.gz are separated by comma, example A1_oligo_R1.gz,A2_oligo_R1.gz. There cannot be a space after a comma.
![1650425147(1)](https://user-images.githubusercontent.com/49019821/164144426-7a83cf83-264a-4129-8a9f-7f9e53609737.jpg)


> I process the raw data and meet this problem <img alt="image" width="1179" src="https://user-images.githubusercontent.com/72308025/163995207-7c07847e-5182-4de9-b70c-46f54e384242.png">
