### ISSUE TITLE
C4单细胞上游分析样本存在多个文件

### ISSUE THREAD

**Issue by ldan999** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#101]
华大工程师您好，我们所拿到的单细胞测序数据中，每个文件夹下面存在多个fq.gz文件，我对于如何使用 dnbc4tools 运行workflow感到困惑，想知道以下参数对应的文件应该如何输入。非常感谢！
--cDNAfastq1 
--cDNAfastq2 
--oligofastq1 
--oligofastq2 
--genomeDir 
--name 
--threads 
![C4文件](https://github.com/user-attachments/assets/8bc83f6d-3816-4eab-8fce-34246171b356)

**Comment by lishuangshuang0616** [comment]
```
$dnbc4tools rna run \
	--cDNAfastq1 /test/data/test_cDNA_R1.fastq.gz \
	--cDNAfastq2 /test/data/test_cDNA_R2.fastq.gz \
	--oligofastq1 /test/data/test_oligo1_1.fq.gz,/test/data/test_oligo2_1.fq.gz \
	--oligofastq2 /test/data/test_oligo1_2.fq.gz,/test/data/test_oligo2_2.fq.gz \
	--genomeDir /database/scRNA/Mus_musculus/mm10  \
	--name test --threads 10
```
这个分为两个样本DA,DB需要分开分析

DA的
```
--cDNAfastq1 E****_L01_53_1.fq.gz,E****_L01_61_1.fq.gz,E****_L01_69_1.fq.gz \
--cDNAfastq1 E****_L01_53_2.fq.gz,E****_L01_61_2.fq.gz,E****_L01_69_2.fq.gz \
--oligofastq1 DA_olgio_1.fq.gz  --oligofastq2 DA_olgio_2.fq.gz
```
注意填写文件路径。其他参考

**Comment by biginfor** [comment]
> ```
> $dnbc4tools rna run \
> 	--cDNAfastq1 /test/data/test_cDNA_R1.fastq.gz \
> 	--cDNAfastq2 /test/data/test_cDNA_R2.fastq.gz \
> 	--oligofastq1 /test/data/test_oligo1_1.fq.gz,/test/data/test_oligo2_1.fq.gz \
> 	--oligofastq2 /test/data/test_oligo1_2.fq.gz,/test/data/test_oligo2_2.fq.gz \
> 	--genomeDir /database/scRNA/Mus_musculus/mm10  \
> 	--name test --threads 10
> ```
> 
> 这个分为两个样本DA,DB需要分开分析
> 
> DA的
> 
> ```
> --cDNAfastq1 E****_L01_53_1.fq.gz,E****_L01_61_1.fq.gz,E****_L01_69_1.fq.gz \
> --cDNAfastq1 E****_L01_53_2.fq.gz,E****_L01_61_2.fq.gz,E****_L01_69_2.fq.gz \
> --oligofastq1 DA_olgio_1.fq.gz  --oligofastq2 DA_olgio_2.fq.gz
> ```
> 
> 注意填写文件路径。其他参考

--cDNAfastq1 E****_L01_53_2.fq.gz,E****_L01_61_2.fq.gz,E****_L01_69_2.fq.gz \ 
这里是应该是 
--cDNAfastq2 E****_L01_53_2.fq.gz,E****_L01_61_2.fq.gz,E****_L01_69_2.fq.gz \ 吧？

**Comment by lishuangshuang0616** [comment]
嗯嗯，是的，我写错了，抱歉

**Comment by ldan999** [comment]
非常感谢您的回复！另外我看到--name需要输入样本ID，请问在这个数据里样本ID是E***吗？还是DA，DB？

**Comment by lishuangshuang0616** [comment]
可以自由命名的，比如DA，DB，展示在报告中的sample name

**Comment by ldan999** [comment]
您好！在填写文件路径后，显示以下报错，请问这是因为什么原因呢？
![6V8%X 9}{HAG(G8K63ZNJBY](https://github.com/user-attachments/assets/5fd88c38-3721-4a0d-b60b-d4942b0a1dcb)
