### ISSUE TITLE
dnbc4tools rna multi 不产生任何结果，但同时没有任何报错

### ISSUE THREAD

**Issue by biginfor** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#102]
尊敬的开发者：
      您好！
      我在使用dnbc4tools rna multi时出现了问题。程序既没有输出，也没有报错。是因为我的list文件有问题吗？
      以下是我使用的的命令行：
      dnbc4tools rna multi \
            --list ${list_file}
           --genomeDir ${genomedir}
           --threads 10
           --outdir ${outdir}
[list_file]
[scRNAseq_meta_multi.txt](https://github.com/user-attachments/files/16729020/scRNAseq_meta_multi.txt)

谢谢！

**Comment by lishuangshuang0616** [comment]
这是为了生成多个样本的shell，然后依然要去跑这些shell，为了方便输入

**Comment by biginfor** [comment]
谢谢！
