### ISSUE TITLE
Concerns Regarding "Sequencing Saturation" in the "DNBelab C4 scRNA-seq v2" Workflow Reports

### ISSUE THREAD

**Issue by nh-codem** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#104]
Our collaborator Recently sequenced the **same library** using both V2 and V3 versions of the chips. We have some questions regarding the interpretation of the pipline report results:

① Based on the **Median UMIs** and **Median Genes** index for each cell, we observed that the average number of UMIs per gene for the V2 chip is about 1, while for the V3 chip, it is close to 3. According to our understanding, the **sequencing saturation** for V3 should be higher than that for V2. However, the reportes show that the **maximum Saturation values**  for V2 reaches nearly 60%, while V3 is below 20%, indicating that the sequencing saturation for V3 is much lower than for V2. This contradicts our intuitive understanding. How should we explain this situation?

② We also observed a significant difference in the sequencing reads counts between the two chips. V2 produced 300M of mRNA reads, while V3 produced 900M. What factors are mainly associated with this difference in sequencing?

![image](https://github.com/user-attachments/assets/b021780c-46ae-4a20-8bbe-20287a5e587c)

We would appreciate your expert explanation on these issues.

**Comment by lishuangshuang0616** [comment]
This result is from Nuclear sample.

The V3 version of the reagent has significantly optimized the mRNA capture capability, especially enhancing the capture of long fragments and intron regions. Compared to the V2 version, V3 captures more mRNA and a higher proportion of introns （increased antisense ratio ）.

 In short, V3 achieves more transcript capture by improving RT reaction efficiency and the binding ability to long fragments, whereas the V2 version is weaker in this aspect and more prone to saturation.

If your research does not specifically focus on low-expression genes or transcripts, the current number of UMIs and genes captured by the V3 version is sufficient to support conventional analysis without the need for additional sequencing. However, if you need to explore the recovery of low-expression genes more deeply, it is recommended to consider adding some additional data.

**Comment by nh-codem** [comment]
> This result is from Nuclear sample.
> 
> The V3 version of the reagent has significantly optimized the mRNA capture capability, especially enhancing the capture of long fragments and intron regions. Compared to the V2 version, V3 captures more mRNA and a higher proportion of introns （increased antisense ratio ）.
> 
> In short, V3 achieves more transcript capture by improving RT reaction efficiency and the binding ability to long fragments, whereas the V2 version is weaker in this aspect and more prone to saturation.
> 
> If your research does not specifically focus on low-expression genes or transcripts, the current number of UMIs and genes captured by the V3 version is sufficient to support conventional analysis without the need for additional sequencing. However, if you need to explore the recovery of low-expression genes more deeply, it is recommended to consider adding some additional data.

Thank you so much for your response.
