### ISSUE TITLE
构建参考基因组索引所需内存

### ISSUE THREAD

**Issue by ldan999** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#106]
华大工程师您好！在构建索引这一步，发现没有生成database这个文件夹，并且生成的文件仅如下图所示，是否是因为内存不够而无法生成更多所需的文件？构建索引这一步大概需要预留多少内存？非常感谢。
![PSYC)7DUK% FML`)8 9%SKE_tmb](https://github.com/user-attachments/assets/049bdd44-69d7-4a93-bb84-1071c49ea82e)

**Comment by lishuangshuang0616** [comment]
你这个目录就相当于database。你的STAR还正在构建过程中，需要比较长的时间，内存的话，人鼠分析使用内存一般在50G即可。占用空间的话预留50G。

**Comment by ldan999** [comment]
好的明白了，非常感谢您的回复！
