### ISSUE TITLE
error: the following arguments are required: --name, --cDNAfastq1, --cDNAfastq2, --oligofastq1, --oligofastq2, --genomeDir

### ISSUE THREAD

**Issue by ldan999** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#107]
华大工程师您好！在运行main workflow这一步，输入文件路径后出现以下报错，请问这是什么原因呢？非常感谢！
![6V8%X 9}{HAG(G8K63ZNJBY](https://github.com/user-attachments/assets/ef140dc9-0f48-47e8-8d22-5e95b0346c0a)

**Comment by lishuangshuang0616** [comment]
别加\ ，那个快速说明里面的\是因为要换行，你这个没有换行就不用加

**Comment by ldan999** [comment]
非常感谢您的回复！
