### ISSUE TITLE
建立参考基因组索引问题

### ISSUE THREAD

**Issue by ldan999** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#108]
技术老师您好！数据所在的盘剩余内存有100多G，但在在建立索引这一步出现了以下问题，想请教您这个应该如何解决？谢谢您！
![_P2KX1T_J(GSI4_%}A4XBV4_tmb](https://github.com/user-attachments/assets/14915db0-9d41-4558-99e5-7dd25bb4a91b)

**Comment by lishuangshuang0616** [comment]
我需要更多的截图，或者你考虑下是否使用内存过少，STAR建库人鼠需要的运行内存mem最好为50G，非存储空间。

**Comment by lishuangshuang0616** [comment]
有跑通吗

**Comment by ldan999** [comment]
正在尝试使用另一台电脑跑单个样本，但是在下载dnbc4tools时出现了问题。
![@OT~KHEE58%CB590C)~$6{4_tmb](https://github.com/user-attachments/assets/961b8453-e8d9-4829-b332-f9af0f0eb120)
