### ISSUE TITLE
细胞数目和质量都很高

### ISSUE THREAD

**Issue by LJIGDBLL** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#115]
开发者您好，我用
DNBelab™ C Series
Single-Cell RNA Analysis Report V2.1.2
![image](https://github.com/user-attachments/assets/418bbacc-665f-4b7a-bc4b-26d80d3fbe83)
分析多个样本拿到的数据都出乎意料的很好，下游分析也没有什么问题。但是有疑虑仅投入了3.3w的细胞，最后能拿到2.6w甚至有个样达到了3w，有点担心这种现象是可以接受的吗？
先前用去年年初的其他版本分析拿到的细胞数多在2w左右
期待您的回答。

**Comment by lishuangshuang0616** [comment]
不确定您的样本是什么类型物种，因为我看到total genes detected 很高不太像是人或者鼠。
- 从表达来看似乎细胞的转录本表达也很高，cell calling计算时通过umi的捕获来鉴定是否为细胞，所以应该会很少有真实细胞被丢弃到背景中的情况。
- 需要看下曲线背景与真实细胞之间是否存在明显的界限。或者是否背景的部分也被纳入到的真实细胞中，来确定鉴定到细胞是否可能存在有背景污染情况。

**Comment by LJIGDBLL** [comment]
是大豆的样品。背景污染的可能性应该很低，
1.3次独立的测序样品结果都类似，捕获细胞数都达到了这么高
2.进行细胞注释以后，似乎cell type specific expression gene都能很好匹配到对应cluster。
以下是更多的信息 似乎也没有被污染
![image](https://github.com/user-attachments/assets/38cd940e-37a0-4bf8-a31a-116b69009a8a)
![image](https://github.com/user-attachments/assets/08954265-9300-4c0b-bd61-e8d0cc598b99)

**Comment by lishuangshuang0616** [comment]
嗯嗯，这个样本来看捕获区域都是集中在exon，非特异性捕获比如intergenic很低。
整体结果捕获的转录本也是很高的。
进行细胞注释以后，似乎cell type specific expression gene都能很好匹配到对应cluster。如果cell marker特异性的表达在对应的细胞群中。结果应该是没什么问题。对于转录本很丰富的样本细胞回收通常会高的。

**Comment by lishuangshuang0616** [comment]
之前的话可能试剂版本也有区别，您之前的数据可能是V2版本，这次的数据是V3版本吗？测序试剂的不同版本对转录本的捕获效率也是存在差异的。

**Comment by LJIGDBLL** [comment]
喔喔，那很可能是算法和试剂盒的共同优化后的正常结果，谢谢您的解答！
