### ISSUE TITLE
Running the main workflow报错

### ISSUE THREAD

**Issue by ldan999** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#116]
技术老师您好！用单细胞数据跑dnbc4tools rna run这一步有获得一些结果文件，但出现了如下报错，想请教您这个该如何解决。非常感谢！
![)W`(X_UOA P$T2O2IXF6EKB](https://github.com/user-attachments/assets/c9bae580-4510-4a4c-a75d-f794e4bcfad8)
![0Y`U~KWM{G6XEHL`HH(EAIL_tmb](https://github.com/user-attachments/assets/e9017c0b-6da1-438d-b929-cce0fc77bd85)
![T1T308ZZ42F%T~3{NDSJXKM](https://github.com/user-attachments/assets/94887a35-4dd7-467d-8932-2581d955fd9a)

**Comment by ldan999** [comment]
![)W`(X_UOA P$T2O2IXF6EKB](https://github.com/user-attachments/assets/c8463005-e5c4-41e2-b0a4-89742398b915)

**Comment by lishuangshuang0616** [comment]
我可以看下log目录的文件吗？这个报错只有这么多信息吗，看错误是在oligo那块断了。

**Comment by lhe999** [comment]
![image](https://github.com/user-attachments/assets/6e2ee6fe-857e-4ba8-a24c-ff9fb0cf9472)
![image](https://github.com/user-attachments/assets/5cd2614e-57dc-4d45-b8b4-a985d3dced67)
![image](https://github.com/user-attachments/assets/f1713a6a-9aef-4529-9768-9042e19eca94)
这是log目录的情况

**Comment by lhe999** [comment]
![image](https://github.com/user-attachments/assets/f80cefea-1528-45f9-8313-45fff251abbb)
这是当时运行的代码和完整的报错信息

**Comment by lishuangshuang0616** [comment]
嗯嗯，合并这个地方内存不够，你的oligo reads很多吗，可以看下oligo的report，然后截取100M就可以了。

**Comment by lhe999** [comment]
非常感谢您的回复！oligo大小有11G，以下是报告里面数据统计的情况，请问截取oligo应该截取哪些部分？可以用什么方法截取？
![image](https://github.com/user-attachments/assets/ade2c2d1-f3d9-4146-b4f2-dba7aaef540d)

**Comment by lishuangshuang0616** [comment]
建议使用seqkit软件，有一个seqkit head 去截取，双端都需要截取，-n 100000000.
你的oligo序列很多，可能你的内存配置较低所以导致错误。

**Comment by ldan999** [comment]
好的！非常感谢！
