### ISSUE TITLE
scRNA run结果解读

### ISSUE THREAD

**Issue by ldan999** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#118]
技术老师您好！目前我完整地运行了单细胞的代码并得到了以下结果文件，请问这是否是正确的结果？这些结果应该如何解读？
此外，如果后续要在R中进一步分析的话，我应该提取哪个文件夹中的文件？非常感谢您的帮助！
![image](https://github.com/user-attachments/assets/c14c965a-d2a0-4779-84a1-c8540f0c7496)

**Comment by lishuangshuang0616** [comment]
结果文件都在output里面，分析的话参考quick start最下面的链接
![image](https://github.com/user-attachments/assets/d9671edb-7832-4b77-bff8-a81f674634c4)

**Comment by lishuangshuang0616** [comment]
分析结果可以看网页报告html

**Comment by ldan999** [comment]
好的明白了！感非常谢！

**Comment by ldan999** [comment]
好的明白了！非常感谢！
