### ISSUE TITLE
error: the following arguments are required: --oligofastq1, --oligofastq2

### ISSUE THREAD

**Issue by Chanspace** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#12]
您好，网络下载的肺组织单细胞核测序数据（如CNS0305928），没有--oligofastq提供下载，该怎么使用呢？

**Comment by Chanspace** [comment]
添加--mixseq貌似也没用

**Comment by lishuangshuang0616** [comment]
您好，CNS0305928数据使用的试剂属于较早版本，没有oligo文库数据。请下载 https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_scRNA-analysis-software 进行分析。

**Comment by liuhang-git** [comment]
https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_scRNA-analysis-software

这个版本为什么只取前50000行作为原始barcode
head -n 50000 ${outdir}/temp/barcode_counts_raw.txt |cut -f1 > ${outdir}/temp/barcode_raw_list.txt

**Comment by hejian41** [comment]
Hi, could you please share the access to demo fastqs including both cDNA and oligo sequences? Thanks!
