### ISSUE TITLE
如何在小鼠参考基因组基础上，构建一个带有EGFP基因或者其他非小鼠基因的参考基因组呢？How can we construct a reference genome with the EGFP gene or other non-mouse genes based on the mouse reference genome?

### ISSUE THREAD

**Issue by XiaoRuipei2024edu** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#128]
华大工程师您好，我在小鼠细胞中过表达了带有EGFP的质粒，所以部分单细胞会表达绿色荧光蛋白（GFP），但是这个基因并不属于小鼠基因，属于水藻水母之类的，也经过了人工修饰。因此在参考基因组比对时，需要将它（GFP基因）加入到小鼠的参考基因组中，才能比对到这个基因的表达量。10X cellranger有相关教程教我们如何构建这样的参考基因组，教程链接在： https://mp.weixin.qq.com/s/vcqRdOjdnI3gaeg97A2IQA ,但这样的方法是否也适用于DNBelab_C的DNBC4tools呢？或者您可否提供一个类似的教程呢，我会非常感激您的解答。

Hello, BGI engineers,
I have overexpressed a plasmid containing the EGFP gene in mouse cells, so some single cells express green fluorescent protein (GFP). However, this gene does not belong to the mouse genome; it originates from organisms like Chlamydomonas or Aequorea victoria, and has been artificially modified. Therefore, when performing reference genome alignment, the GFP gene needs to be added to the mouse reference genome in order to accurately align and quantify its expression.
There is a relevant tutorial on 10X Cell Ranger that teaches us how to build such a reference genome. The tutorial link is: https://mp.weixin.qq.com/s/vcqRdOjdnI3gaeg97A2IQA.
Would this method also be applicable to DNBelab_C's DNBC4tools? Or could you provide a similar tutorial? I would greatly appreciate your assistance.

**Comment by lishuangshuang0616** [comment]
gfp
```
cat GFP_orig.fa | sed s/L29345\.\1\ Aequorea\ victoria\ green\-fluorescent\ protein\ \(GFP\)\ mRNA\,\ complete\ cds/GFP/ > GFP.fa
echo -e 'GFP\tunknown\tgene\t1\t922\t.\t+\t.\tgene_id "GFP"; gene_name "GFP"; gene_biotype "protein_coding";' > GFP.gtf
echo -e 'GFP\tunknown\texon\t1\t922\t.\t+\t.\tgene_id "GFP"; transcript_id "GFP"; gene_name "GFP"; gene_biotype "protein_coding";' >> GFP.gtf
```

fasta
```
cat  GFP.fa >>Mus_musculus.GRCm38.dna.primary_assembly.fa
grep ">" Mus_musculus.GRCm38.dna.primary_assembly.fa
```
gtf
```
cat  GFP.gtf >> Mus_musculus.GRCm38.93.gtf
tail  Mus_musculus.GRCm38.93.gtf
```

和10x不同的是，dnbc4tools的gtf需要加上gene行或者transcript行

**Comment by XiaoRuipei2024edu** [comment]
感谢您耐心的解答，按照您的建议，我修改了参考基因组，但是我未能成功比对到GFP基因。我向您展示我的操作过程及部分结果，请您帮忙看一下我的做法是否正确。我的EGFP序列（过表达质粒测序，其中EGFP测序结果）是：ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCCTGGTCGAGCTGGACGGCGACGTAAACGGCCACAAGTTCAGCGTGTCTGGCGAGGGCGAGGGCGATGCCACCTACGGCAAGCTGACCCTGAAGTTCATCTGCACCACCGGCAAGCTGCCCGTGCCCTGGCCCACCCTCGTGACCACCCTGACCTACGGCGTGCAGTGCTTCAGCCGCTACCCCGACCACATGAAGCAGCACGACTTCTTCAAGTCCGCCATGCCCGAAGGCTACGTCCAGGAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCGCCGAGGTGAAGTTCGAGGGCGACACCCTGGTGAACCGCATCGAGCTGAAGGGCATCGACTTCAAGGAGGACGGCAACATCCTGGGGCACAAGCTGGAGTACAACTACAACAGCCACAACGTCTATATCATGGCCGACAAGCAGAAGAACGGCATCAAGGCGAACTTCAAGATCCGCCACAACATCGAGGACGGCAGCGTGCAGCTCGCCGACCACTACCAGCAGAACACCCCCATCGGCGACGGCCCCGTGCTGCTGCCCGACAACCACTACCTGAGCACCCAGTCCGCCCTGAGCAAAGACCCCAACGAGAAGCGCGATCACATGGTCCTGCTGGAGTTCGTGACCGCCGCCGGGATCACTCTCGGCATGGACGAGCTGTACAAGTAA。
因此我这样做：
vi GFP_orig.fa
在其中输入：>L29345.1 Aequorea victoria green-fluorescent protein (GFP) mRNA, complete cds
ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCCTGGTCGAGCTGGACGGCGACGTAAACGGCCACAAGTTCAGCGTGTCTGGCGAGGGCGAGGGCGATGCCACCTACGGCAAGCTGACCCTGAAGTTCATCTGCACCACCGGCAAGCTGCCCGTGCCCTGGCCCACCCTCGTGACCACCCTGACCTACGGCGTGCAGTGCTTCAGCCGCTACCCCGACCACATGAAGCAGCACGACTTCTTCAAGTCCGCCATGCCCGAAGGCTACGTCCAGGAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCGCCGAGGTGAAGTTCGAGGGCGACACCCTGGTGAACCGCATCGAGCTGAAGGGCATCGACTTCAAGGAGGACGGCAACATCCTGGGGCACAAGCTGGAGTACAACTACAACAGCCACAACGTCTATATCATGGCCGACAAGCAGAAGAACGGCATCAAGGCGAACTTCAAGATCCGCCACAACATCGAGGACGGCAGCGTGCAGCTCGCCGACCACTACCAGCAGAACACCCCCATCGGCGACGGCCCCGTGCTGCTGCCCGACAACCACTACCTGAGCACCCAGTCCGCCCTGAGCAAAGACCCCAACGAGAAGCGCGATCACATGGTCCTGCTGGAGTTCGTGACCGCCGCCGGGATCACTCTCGGCATGGACGAGCTGTACAAGTAA
保存后退出vi GFP_orig.fa
接下来在GFP_orig.fa基础上修改得到了GFP.fa   
cat GFP_orig.fa | sed s/L29345\.\1\ Aequorea\ victoria\ green\-fluorescent\ protein\ \(GFP\)\ mRNA\,\ complete\ cds/GFP/ > GFP.fa
接下来将其加入原参考基因组
cat  GFP.fa >>GRCm38.primary_assembly.genome.fa
grep ">" GRCm38.primary_assembly.genome.fa 看到了GFP加入成功。
<img width="802" alt="image" src="https://github.com/user-attachments/assets/8816e442-7c2f-4756-b540-161aefee46b8">
<img width="505" alt="image" src="https://github.com/user-attachments/assets/79a06165-b27a-4bff-a13d-f6cf187cbee8">
通过tail -n 20 GRCm38.primary_assembly.genome.fa可以看到GFP加入了参考基因组，但是看起来似乎和原本的参考基因组不太一样，新加入的EGFP序列在fa文件中不会自动换行，这会有影响吗？
<img width="1115" alt="image" src="https://github.com/user-attachments/assets/4374a7e1-fc51-4921-926d-02a712545b94">
接下来我也按照您说的修改了GTF文件（我的基因序列长度是723）所以写的723：
echo -e 'GFP\tunknown\tgene\t1\t723\t.\t+\t.\tgene_id "GFP"; gene_name "GFP"; gene_biotype "protein_coding";' > GFP.gtf
echo -e 'GFP\tunknown\texon\t1\t723\t.\t+\t.\tgene_id "GFP"; transcript_id "GFP"; gene_name "GFP"; gene_biotype "protein_coding";' >> GFP.gtf
cat  GFP.gtf >> gencode.vM23.primary_assembly.annotation.gtf
tail gencode.vM23.primary_assembly.annotation.gtf     看到了gtf文件末尾成功加入了GFP基因（虽然我不知道对不对）
<img width="1115" alt="image" src="https://github.com/user-attachments/assets/8895a27d-f391-473e-9e6e-4b626227e79a">
接下来我使用新得到的fa文件和GTF文件重新mkgft和mkref建索引。以及rna run跑完了上游流程。在output文件中feature.tsv.gz依然没有比对到GFP这个基因，由于我在做单细胞测序之前的流式细胞术中是可以检测到GFP的，而这段EGFP的序列也是我拿GFP过表达质粒去测序得到的，因此我觉得部分细胞是有表达GFP的，也可以比对到的。
而且我使用samtools view final_sorted.bam | grep "GFP"检查，好像可以看到GFP基因？我看不懂，需要您指导一下。
<img width="1113" alt="image" src="https://github.com/user-attachments/assets/a01b35cf-3c10-4ab3-9987-91f00d83ad35">
所以我想请问我的参考基因组构建的是否有问题呢。 如果我参考基因组构建没问题，有没有可能是我选取的序列有问题呢，我过表达质粒上对EGFP测序序列是否要整个复制进入GFP.fa文件呢，还有是否需要什么3‘UTR和poliA序列？我该怎么优化我的参考基因组呢。samtools view final_sorted.bam | grep "GFP"能看到GFP是否说明我其实有比对到GFP呢？我feature.tsv.gz文件中是没有GFP这个基因的。非常感谢您耐心的解答。

**Comment by lishuangshuang0616** [comment]
从结果来看比对是能比对上，但是确没注释上，可以看下log目录内的日志上有没有信息显示该基因被过滤。
```
tail gencode.vM23.primary_assembly.annotation.gtf | cat -A
```
看下gtf格式是否有问题

**Comment by XiaoRuipei2024edu** [comment]
非常感谢您耐心的解答。按照您的建议，我查看并在log文件中检索“GFP”，确定log目录内的日志上没有信息显示该基因被过滤。
<img width="1121" alt="image" src="https://github.com/user-attachments/assets/933acbde-0406-43d2-9cab-ec96ca04a78b">


<img width="1116" alt="image" src="https://github.com/user-attachments/assets/859f05e4-3bd3-49d1-b4d5-8fa060c5447d">

此外我检查了gtf文件的格式，
查看gtf格式（tail gencode.vM23.primary_assembly.annotation.gtf | cat -A）的结果是有GFP基因：
<img width="1110" alt="image" src="https://github.com/user-attachments/assets/a79cc6d0-1a66-48cf-80d8-1c534ddb0942">
但是我进一步查看genes.filter.gtf 时发现了问题，genes.filter.gtf 中没有看到GFP基因。
<img width="1115" alt="image" src="https://github.com/user-attachments/assets/e2f40971-7c5c-421a-b74c-d5527436bbc8">
<img width="649" alt="image" src="https://github.com/user-attachments/assets/0419c91a-0879-470b-a821-7795450effa3">
所以我的gtf文件格式是否需要进一步修正，使得genes.filter.gtf 中能够包含“GFP"基因呢。

**Comment by lishuangshuang0616** [comment]
- 方法1：
直接cat到genes.filter.gtf
```
cat  GFP.gtf >> genes.filter.gtf
```

- 方法2
分析时用的是过滤后的gtf，所以你放在原始的里面没有用。
如果你是先放在原始的gtf再过滤的，那么你需要考虑gene type的tag。保持一致。所以应该是：
```
echo -e 'GFP\tunknown\tgene\t1\t922\t.\t+\t.\tgene_id "GFP"; gene_name "GFP"; gene_type "protein_coding";' > GFP.gtf
echo -e 'GFP\tunknown\texon\t1\t922\t.\t+\t.\tgene_id "GFP"; transcript_id "GFP"; gene_name "GFP"; gene_type "protein_coding";' >> GFP.gtf
```
然后再去cat到gencode.vM23.primary_assembly.annotation.gtf去进行dnbc4tools tools mkgtf过滤

**Comment by XiaoRuipei2024edu** [comment]
感谢您耐心的解答，按照您的方法2，
echo -e 'GFP\tunknown\tgene\t1\t723\t.\t+\t.\tgene_id "GFP"; gene_name "GFP"; gene_type "protein_coding";' > GFP.gtf
echo -e 'GFP\tunknown\texon\t1\t723\t.\t+\t.\tgene_id "GFP"; transcript_id "GFP"; gene_name "GFP"; gene_type "protein_coding";' >> GFP.gtf
cat GFP.gtf >> gencode.vM23.primary_assembly.annotation.gtf
在dnbc4tools tools mkgtf过滤后的genes.filter.gtf成功看到了GFP基因。
<img width="1116" alt="image" src="https://github.com/user-attachments/assets/77174c1c-4f09-4f9e-bec0-193cfc909c16">
接下来的分析也成功地在表达矩阵中看到了GFP基因的表达。非常感谢您一直耐心的解答。祝您工作顺利！

**Comment by linrisheng8** [comment]
您好，我也是想在单细胞中检测GFP基因的表达情况，但是不确定是否能够被读到，因为我的ployA前面还有WPRE元件（KI的小鼠本身也有WPRE元件在，因此无法无法区分来自载体还是小鼠），所以不确定GFP是否能够被测到。请问您的载体结构是什么样的呢？
