### ISSUE TITLE
Error Gene symbol in 03.analysis/Clustering marker gene table

### ISSUE THREAD

**Issue by myshu2017-03-14** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#13]
在04.report/*report.html结果中的ANALYSIS的marker基因表格中导出的基因symbol存在错误：
![image](https://user-images.githubusercontent.com/26398036/198941601-e39ab366-f7f7-44e6-9892-8bc8bf7c3cd3.png)
比如这里的AAK1.1、AAK1.2和AAK1.3在参考基因组中是不存在的，参考基因组中只有AAK1这一个基因，通过测试代码，发现是在输出"marker.csv"时表格出错。以下是我的测试代码：
![533e7ad931fc45dbc42951b0b0f5f00](https://user-images.githubusercontent.com/26398036/198943288-ec24dd56-72d0-4184-aa22-a46d02c23040.jpg)

**Comment by lishuangshuang0616** [comment]
Thank you very much for your feedback, the gene column should be used here instead of the column name, we will modify it in the next version.
