### ISSUE TITLE
默认情况下rna run 结果是否包括内含子

### ISSUE THREAD

**Issue by evewu2002** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#136]
![image](https://github.com/user-attachments/assets/36feb5a2-18bb-4fd7-bf64-d6f03b7f7295)
我的实验希望保留内含子区域信息进行分析，请问默认情况下rnarun是否包含内含子信息，如果不包含，能否调整参数使其不要过滤内含子？

**Comment by lishuangshuang0616** [comment]
默认包含

**Comment by evewu2002** [comment]
> 默认包含

感谢您的回答
