### ISSUE TITLE
Errors in using DNBC4tools multi features

### ISSUE THREAD

**Issue by Gin-Wang** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#14]
hi, i'm testing DNBC4tools in conda for future analysis. it is going on well when i using feature "DNBC4tools run". But there is something wrong when i applied "DNBC4tools multi" for 2 or more samples. Ther veision is 2.0.7 and here is the error.

Traceback (most recent call last):
  File "/home/software/miniconda3/envs/DNBC4tools/bin/DNBC4tools", line 8, in <module>
    sys.exit(main())
  File "/home/software/miniconda3/envs/DNBC4tools/lib/python3.8/site-packages/DNBC4tools/DNBC4tools.py", line 43, in main
    args.func(args)
  File "/home/software/miniconda3/envs/DNBC4tools/lib/python3.8/site-packages/DNBC4tools/tools/multi.py", line 64, in multi
    Multi_list(args).run()
  File "/home/software/miniconda3/envs/DNBC4tools/lib/python3.8/site-packages/DNBC4tools/tools/multi.py", line 27, in run
    cDNAr1 = lst[1].split(';')[0]
IndexError: list index out of range

There were two .sh files that were generated after "DNBC4tools multi" and each one is the command of "DNBC4tools run" just as I tested successful before.

**Comment by lishuangshuang0616** [comment]
Can you take a screenshot of the sample list file? @Gin-Wang

**Comment by Gin-Wang** [comment]
> Can you take a screenshot of the sample list file? @Gin-Wang


![image](https://user-images.githubusercontent.com/36735223/208066495-c7ad9cbc-9a40-47d1-a121-d3765785ae2e.png)
[samplelist.txt](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/files/10244471/samplelist.txt)
 thanks, there is the screenshot and samplelist file @lishuangshuang0616

**Comment by lishuangshuang0616** [comment]
![image](https://user-images.githubusercontent.com/49019821/208112338-d4ba06b7-2f5d-42ca-9f7b-c05f08f543ad.png)
Just because there are blank lines at the bottom, next updates will adjust not to read blank lines。

**Comment by Gin-Wang** [comment]
> ![image](https://user-images.githubusercontent.com/49019821/208112338-d4ba06b7-2f5d-42ca-9f7b-c05f08f543ad.png) Just because there are blank lines at the bottom, next updates will adjust not to read blank lines。

thanks, now it runs successfully and generate 2 sh files. Actually I thought it could run next steps automatically but it just help me generate the run command lines.
