### ISSUE TITLE
当scRNA-seq单样本有多个技术重复时，该如何运行命令？

### ISSUE THREAD

**Issue by hyjforesight** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#140]
MGI，您好！
感谢分享此流程工具！
我有3个不同数据结构的患者数据，如下图所示，均是从GSA公共数据库下载下来的。我已经阅读了dnbc4tools的教程，按照我的理解，我为每位患者分别写了dnbc4tools rna run的运行代码，能否请您帮忙看一下是否正确？
<img width="444" alt="image" src="https://github.com/user-attachments/assets/d032653b-2eaa-421e-a3e1-6785e08f9701" />

患者P24，单生物样本，3个技术重复，每个技术重复的cdna和oligo仅有1组fastq，按我的理解，运行代码应为：
```linux
dnbc4tools rna run --cDNAfastq1 HRR1395066_R1.fq.gz,HRR1395068_R1.fq.gz,HRR1395070_R1.fq.gz --cDNAfastq2 HRR1395066_R2.fq.gz,HRR1395068_R2.fq.gz,HRR1395070_R2.fq.gz --oligofastq1 HRR1395067_R1.fq.gz,HRR1395069_R1.fq.gz,HRR1395071_R1.fq.gz --oligofastq2 HRR1395067_R2.fq.gz,HRR1395069_R2.fq.gz,HRR1395071_R2.fq.gz --genomeDir /database/scRNA/Homo_sapiens --name test --threads 10
```

患者P27，单生物样本，无技术重复，cdna中有2组fastq。
对于单个技术重复的P27，为什么他的cDNA里面会有2组fastq，但是oligo只有1组fastq文件？如果按照P24的逻辑，在`--cDNAfastq`中以逗号输入多个fastq文件，那怎么区分这些fastq是来自于一个cDNA的多个fastq，还是来自于多个技术重复多个cDNA各自的单个fastq？运行代码是否应该写成：
```linux
dnbc4tools rna run --cDNAfastq1 HRR1395072_R1.fq.gz,HRR1395073_R1.fq.gz --cDNAfastq2 HRR1395072_R2.fq.gz,HRR1395073_R2.fq.gz --oligofastq1 HRR1395074_R1.fq.gz --oligofastq2 HRR1395074_R2.fq.gz --genomeDir /database/scRNA/Homo_sapiens --name test --threads 10
```

患者P30，单生物样本，2个技术重复，每个技术重复的cdna中有2组fastq。相对于P24和P27，P30令我更混乱。运行代码是否应该写成：
```linux
dnbc4tools rna run --cDNAfastq1 HRR1395075_R1.fq.gz,HRR1395076_R1.fq.gz,HRR1395078_R1.fq.gz,HRR1395079_R1.fq.gz --cDNAfastq2 HRR1395075_R2.fq.gz,HRR1395076_R2.fq.gz,HRR1395078_R2.fq.gz,HRR1395079_R2.fq.gz --oligofastq1 HRR1395077_R1.fq.gz,HRR1395080_R1.fq.gz --oligofastq2 HRR1395077_R2.fq.gz,HRR1395080_R2.fq.gz --genomeDir /database/scRNA/Homo_sapiens --name test --threads 10
```

另外，教程里面有涉及到多样本操作，但是我不是特别理解。按此流程创建`sample1.sh，sample2.sh，sample3.sh`共3个shell文件，和我在一个shell里放这3条运行代码有何不同？
<img width="783" alt="image" src="https://github.com/user-attachments/assets/720a3f9f-2fc4-411d-8b93-e3059f38b387" />

谢谢指导！

**Comment by lishuangshuang0616** [comment]
样本的技术重复应该是分别建了多个文库，所以需要分开跑，每个技术重复都跑run，我的理解。
逻辑：同一个cell barocde是否对应同一个细胞，没法对应就得分开分析。所以只能是同一文库的多次测序或者多个测序能放在一起分析。

**Comment by lishuangshuang0616** [comment]
同一个技术重复存在多个fastq是因为加测或者测序时分在不同lane不同芯片测序得到测序量。需要放在一起分析跑一个run。

**Comment by lishuangshuang0616** [comment]
多样本操作和你的没什么不同，主要是为了操作简便。

**Comment by hyjforesight** [comment]
> 样本的技术重复应该是分别建了多个文库，所以需要分开跑，每个技术重复都跑run，我的理解。 逻辑：同一个cell barocde是否对应同一个细胞，没法对应就得分开分析。所以只能是同一文库的多次测序或者多个测序能放在一起分析。

@lishuangshuang0616 谢谢您的回复！
所以是不是可以这么理解：
1、SC_P24所谓的3个技术重复，实际上是同一个样本解离出来的单细胞分批上样所获得的3个不同文库（所以会有3个oligo文件夹），可以理解为3个不同生物重复，所以应该一个一个run分开来运行。
2、真正的技术重复（即为了增加测序量，将同一个文库点在同一Lane的不同孔中进行测序）应该会在一个cDNA文件夹中生成多个fastq文件组。
3、综上所述：放在一个run中还是分开run，取决于oligo文件夹，因为oligo对应文库（一个文库只对应一个oligo，所以只有1组fastq），cdna文件夹对应测序读数（可以有多组fastq）

另外，我将SC_P24的3个技术重复放在一个run里面跑，未报错，是否说明一个cell对应了一个barcode，可以放在一个run里面跑？
以下是我放在一个run里面跑的结果（细胞数13560）：
<img width="824" alt="image" src="https://github.com/user-attachments/assets/aecad83a-a7bf-48e6-bb29-1434c1b40f5c" />
以下是3个技术重复分别独立跑的结果（细胞数=4606+3771+4569=12946）：
<img width="821" alt="image" src="https://github.com/user-attachments/assets/bb1cc673-8106-4907-8875-ff4e6e55e5d7" />
<img width="833" alt="image" src="https://github.com/user-attachments/assets/728d1e52-3340-4a85-8816-93dea67a2af6" />
<img width="838" alt="image" src="https://github.com/user-attachments/assets/abf205e5-8dc6-4d12-89a2-221af09a4d26" />

**Comment by lishuangshuang0616** [comment]
1.同一个样本分批上样，那么就是3个文库，cDNA和oligo都有三对，应该分开run。
2.不是这样理解，我理解的技术重复的意思是对同一个样本的不同建库，应该当成多个run去处理。dnbc4tools支持一个文库存在多个fastq，这样可以省略合并fastq序列，直接分析，在加测或者多条lane的数据会比较方便。你说的真正的技术重复只是数据的加测，并不是技术重复，技术重复是对一个样本多次上样建库来验证是否存在其他的影响降低偏差。
3.和oligo无关，一个文库也可以有多个oligo的fastq（即加测和多条lane多张芯片数据）。是不是需要分开还是看你的实验是不是同一个文库。
4.肯定不会报错，因为就算是多个样本的数据放在一起跑也不会报错，因为cell barcode的种类非常的多，那么几千个细胞能够占用的cell barcode其实是非常低的，三个样本overlap的cell barcode也不会很多，但是这样可能会导致一些错误。比如一个cell barcode在其中两个是背景，在第三个是细胞的，那么这个cell barcode被认定为细胞的时候就会带有背景的表达，这样都是不正确的。所以能不能放在一起分析，必须要看是不是同一个文库的数据。

**Comment by hyjforesight** [comment]
明白了，总结起来就是取决于一点：同一文库，合并run；非同一文库，分开run。光看数据形式是看不出来的，关键是要问原作者他们究竟是怎么制库和测序的。
