### ISSUE TITLE
Error in DNBC4tools run

### ISSUE THREAD

**Issue by shiyuzhang98** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#17]
Thanks for the good tool. But I met an error when running DNBC4tools run:
![Snipaste_2023-03-07_21-44-44](https://user-images.githubusercontent.com/74309824/223440605-633ac801-d5f7-42a8-956f-1368751c2105.png)
![Snipaste_2023-03-07_21-42-16](https://user-images.githubusercontent.com/74309824/223440649-e37cc36a-f0d2-431f-b167-f744ede6eea8.png)
![Snipaste_2023-03-07_21-43-18](https://user-images.githubusercontent.com/74309824/223440663-7b33fef3-04b2-4b65-b5c4-0ae127821229.png)

**Comment by lishuangshuang0616** [comment]
![image](https://user-images.githubusercontent.com/49019821/223591076-e0618887-1dc3-4e81-9e48-0185d9592be3.png)
some problems in fastq? @Shi-YuZhang

**Comment by shiyuzhang98** [comment]
I had multiple `.fq.gz` files in L01/2/3/4 directory respectively and I merged them using `cat XXX/L01/*_1.fq.gz > XXX_L01_1.fq.gz` or `cat XXX/L01/*_2.fq.gz > XXX_L01_2.fq.gz`. I'm not sure if this is right.
![image](https://user-images.githubusercontent.com/74309824/223604932-beda519f-be1b-405e-acca-cf677e25d650.png)

**Comment by lishuangshuang0616** [comment]
You seem to have merged *_undecoded_1.fq.gz into it. This fastq sequence does not cut the index and is a little longer than the others. @Shi-YuZhang

**Comment by shiyuzhang98** [comment]
You mean I should not merge *_undecoded_1.fq.gz in every lane  in cDNA directory and Oligo directory?

**Comment by lishuangshuang0616** [comment]
Does your cDNA and oligo library have no corresponding barcode, do you need all the fastq in the lane? If it is, then should not merge undecoded fastq.

**Comment by shiyuzhang98** [comment]
Sorry, I am a novice in processing data.Can you tell me how to confirm whether there is a corresponding barcode? And can you explain when I need all fastqs and when i do not？Thanks in advance.

**Comment by lishuangshuang0616** [comment]
您好，样本构建文库时都会加上index来区分样本，下机的测序数据需要靠index拆分来知道每个fastq对应的是哪个样本。我不确定你是否需要将一条lane里面所有的fastq合并当作一个样本的数据（如果是，合并时也不要将*_undecoded_*.fq.gz合并进去，这个是拆分时没有拆出来的文库，R2的测序长度比有index的文库长）。通常，一个样本会对应一个index或多个index，只需要使用对应index的fastq来进行分析。先确认你的样本对应的index，然后找到该index的fastq用于分析。 @Shi-YuZhang

**Comment by shiyuzhang98** [comment]
Thanks, it works now.
