### ISSUE TITLE
parseFq 报错 SAW-A10400

### ISSUE THREAD

**Issue by DrFengchenzhao** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#18]
开发者你们好。我在使用v2.0.7的singularity进行分析，其他样本均顺利跑完，但有一个样本出现了如下错误：

<img width="651" alt="SCR-20230308-vz0" src="https://user-images.githubusercontent.com/29920143/223748307-572b78d1-5424-4882-9f28-176a4d2f4c69.png">

01 data其余步骤如比对均正常进行，但由于parseFq没有正常进行，后续需要Index.fq.gz的流程也无法进行。现在卡在01 data。
<img width="948" alt="SCR-20230308-w08" src="https://user-images.githubusercontent.com/29920143/223748780-72c56372-13f1-4598-acc5-28ac4fc6c967.png">

我想知道这个错误 SAW-A10400 意味着什么？我该如何更改，谢谢！

**Comment by lishuangshuang0616** [comment]
Hello, from the error report, it seems that there is a problem with the fastq file of oligo. There is a read length of 0 , so the recognition position is not recognized. Please check your fastq file。 @DrFengchenzhao

**Comment by DrFengchenzhao** [comment]
谢谢
