### ISSUE TITLE
Error code: SAW-A10400 & Where can I find source code for scStar and Anno?

### ISSUE THREAD

**Issue by divinomas** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#19]
I have tried to run DNBelab_C_Series_HT_scRNA-analysis with both conda and docker versions on a node with 32 cpu cores and 128 G memory. However, both approaches terminated with error after the scStar step, since SAW-A10400 error occurred and no 01.data/cDNA_barcode_counts_raw.txt produced by the following Anno step.
This SAW-A10400 error might be associated with 
what():  basic_string::substr: __pos (which is 37) > this->size() (which is 30)

I suspected the wrong barcode/argument used and consulted our sequencing providers, however the same pipeline and default running parameters were claimed by them.
So, how this happened? If the source code of scStar and Anno could be publicly accessed, this issue could be more easily understood.
Thanks. 

![image](https://user-images.githubusercontent.com/12946399/224865616-f781d6c8-570d-43e0-9f39-3a8a765bdfc3.png)

**Comment by lishuangshuang0616** [comment]
Judging from the error report, there is no dark reaction in the automatic detection of your cDNA, but there are 30bp reads in the analysis. Do you merge multiple fastqs, and these fastqs are not of the same length?

**Comment by divinomas** [comment]
Thanks for your kind reply. 
Only one file was input for each cDNAfastq1/2 and oligofastq1/2. But I have no idea whether each .fa.gz was merged before sent to us. Could any tools help to check and split reads easily? or how should I set the argument to allow the pipeline run with merged unequal-sized libraries?

**Comment by lishuangshuang0616** [comment]
It is not recommended to combine fastq files of multiple cDNA or oligo libraries before analysis. **Multiple files should be separated by commas as input**. The principle of automatically obtaining structure information is to take the first 100,000 reads for analysis. If there are multiple files, each will be detected. If the structure is different, fastq.gz can only be cut in advance to make it the same length. You can use **seqkit stats** to check whether the length of fastq is consistent.

**Comment by divinomas** [comment]
Great suggestion. While seqkit stats show the oligo_R1 are uniformly 30bp, and oligo_R2 are 100bp in length, cDNA_R1 lengths vary in (30, 150) with the mean 61.6, and  cDNA_R2 in (100, 150) with mean 113.2. 
Then the best option is to find the library merge point, split around it and re-run the pipeline? Or other simpler operations could be done?

**Comment by lishuangshuang0616** [comment]
Since the fastq.gz files of different lengths are merged, it is necessary to disassemble the fastq.gz of the cDNA according to the length, and then cut the 150bp into 30bp (obtained according to the structural position). I'll provide you with a python script, **waiting.**

**Comment by lishuangshuang0616** [comment]
Only need to process the R1 of cDNA, cut 150bp into 30bp, it is relatively slow to process such a large fastq.gz, it is recommended to use `seqkit split2 -s 20000000 -1 test_L01_1_1.fq.gz -O /outdir/split_fq`, and then use the script process the split files.
`python cut_fastq_length.py --indir /outdir/split_fq --threads 10`. 
After the analysis is complete, manually cat *.processed.gz together in order
[cut_fastq_length.py](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/files/10976697/cut_fastq_length.txt)
Different versions of the chemisty cut off the position is not the same，script is V2
![image](https://user-images.githubusercontent.com/49019821/225227861-efc0e66c-f418-486f-8b17-41f2432865cc.png)

**Comment by divinomas** [comment]
Many thanks to [lishuangshuang0616](https://github.com/lishuangshuang0616) for your effort. I will try it asap.
From your code, it seems sequences after 47 in a read longer than 30 are useless or repeated from the leading ones. As I can't retrieve any detailed document about DNBC4 scRNA-seq library, many questions like this remain...

**Comment by lishuangshuang0616** [comment]
https://www.mgi-tech.com/download/files/p/6
![image](https://user-images.githubusercontent.com/49019821/225281502-f2213315-ac49-48c6-a75b-5fd947d2e14a.png)

Refer to this
