### ISSUE TITLE
About Barcode correction

### ISSUE THREAD

**Issue by 10KGenomics** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#2]
Hello, I would like to ask whether this software can perform barcode correction. In one case, there are two kinds of beads in the oil drop, but only one cell.
in this scenario, one cell will split its transcripts across two barcodes and appear like two beads。
In this case, we should correct and combine the two barcodes to avoid errors.

**Comment by lishuangshuang0616** [comment]
A droplet contains two kinds of beads, and the functions of the two kinds of  beads are different. 
We call them cell beads and index_carrier beads. 
The function of cell beads is to distinguish cells, and the function of index_carrier beads is to combine cell beads in a droplet (there will be not only one cell beads in one droplet, conforms to a Poisson distribution).
 We will perform barcode correction for cell beads and index_carrier beads (Hamming distance 1)。

**Comment by caijingtao1993** [comment]
> A droplet contains two kinds of beads, and the functions of the two kinds of beads are different. We call them cell beads and index_carrier beads. The function of cell beads is to distinguish cells, and the function of index_carrier beads is to combine cell beads in a droplet (there will be not only one cell beads in one droplet, conforms to a Poisson distribution). We will perform barcode correction for cell beads and index_carrier beads (Hamming distance 1)。


> A droplet contains two kinds of beads, and the functions of the two kinds of beads are different. We call them cell beads and index_carrier beads. The function of cell beads is to distinguish cells, and the function of index_carrier beads is to combine cell beads in a droplet (there will be not only one cell beads in one droplet, conforms to a Poisson distribution). We will perform barcode correction for cell beads and index_carrier beads (Hamming distance 1)。



> 一个液滴包含两种珠子，两种珠子的作用是不同的。 我们称它们为细胞珠和 index_carrier 珠。 细胞珠的作用是区分细胞，index_carrier珠的作用是将细胞珠结合在一个液滴中（一个液滴中不会只有一个细胞珠，符合泊松分布）。 我们将对细胞珠和 index_carrier 珠进行条形码校正（汉明距离 1）。

 there are two kinds of  cell beads in the oil drop, but only one cell. in this scenario, one cell will split its transcripts across two cell barcodes and appear like two cell beads. You mean index_ Carrier beads will correct the two cell beads to become a cell beads?

**Comment by 10KGenomics** [comment]
> A droplet contains two kinds of beads, and the functions of the two kinds of beads are different. We call them cell beads and index_carrier beads. The function of cell beads is to distinguish cells, and the function of index_carrier beads is to combine cell beads in a droplet (there will be not only one cell beads in one droplet, conforms to a Poisson distribution). We will perform barcode correction for cell beads and index_carrier beads (Hamming distance 1)。

 there are two kinds of  cell beads in the oil drop, but only one cell. in this scenario, one cell will split its transcripts across two cell barcodes and appear like two cell beads. You mean index_ Carrier beads will correct the two cell beads to become a cell beads?
