### ISSUE TITLE
Error: Cannot find input file or dir ~/fastq/pig/Pig_spinal_cord_cDNA1_2.fq.gz.

### ISSUE THREAD

**Issue by zhangw376** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#20]
cDNAfastq1 有1_1，1_2，1_3时候，用DNBC4tools run --cDNAfastq1 ~/fastq/pig/Pig_spinal_cord_cDNA1_1.fq.gz,~/fastq/pig/Pig_spinal_cord_cDNA1_2.fq.gz,~/fastq/pig/Pig_spinal_cord_cDNA1_3.fq.gz只能读到1_1, 报错Error: Cannot find input file or dir ~/fastq/pig/Pig_spinal_cord_cDNA1_2.fq.gz.

**Comment by lishuangshuang0616** [comment]
Are you sure it’s `~/fastq/pig/Pig_spinal_cord_cDNA1_2.fq.gz` and not `/fastq/pig/Pig_spinal_cord_cDNA1_2.fq.gz`? You can manually check if the file exists using the **less** command.

**Comment by zhangw376** [comment]
it is ~/, in my home directory, and I have solved this problem by merging these sub files into one file, but I think maybe there is a bug. thanks~
