### ISSUE TITLE
D2C软件输入文件为.bam 输出文件的.bam无内容。

### ISSUE THREAD

**Issue by MitochondriaATP** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#23]
你好：
D2C 软件（scATAC-seq）：通过BAP算法将一个液滴中多个beads关联到一个细胞上，这个软件目前我发现输入.bam文件后，输出的.bam文件没有内容，请问该怎么解决。

**Comment by lishuangshuang0616** [comment]
您好，dev版本D2C的输入bam还没有适配，后续更新会适配。

**Comment by MitochondriaATP** [comment]
请问，大概什么时间会更新-D2C软件适配输入文件为bam文件。
