### ISSUE TITLE
请问D2C软件，什么时候会更新输入文件为bam，输出文件为bam。同时发现用bap2软件做barcode merge 无法适配华大scATAC-seq产生的bam（chromap)。因此希望尽快能更新适配bam的D2C软件

### ISSUE THREAD

**Issue by MitochondriaATP** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#26]

**Comment by lishuangshuang0616** [comment]
Use the following steps ,using dnbc4tools 2.1.0 software d2c

chromap --preset atac -o aln.sam --SAM 
samtools view -S -b aln.sam > aln.bam
d2c merge -i aln.bam

**Comment by lishuangshuang0616** [comment]
dnbc4tools 2.1.2 can generate bam
