### ISSUE TITLE
What are the major differences to the previous software?

### ISSUE THREAD

**Issue by m-fayer** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#27]
Hi,

I noticed that there is another similar software ([DNBelab_C_Series_scRNA-analysis-software](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_scRNA-analysis-software)) also from MGI. What are their major differences? Do you still recommand use the previous one? I understand there is a HT (high-throughput) in this software. Thanks.

**Comment by lishuangshuang0616** [comment]
The HT version（***DNBelab_C_Series_HT_scRNA-analysis-software***） is a reagent adapted to the presence of both cDNA and oligo libraries. The reagents include scRNAHTv1 and scRNAHTv2. All currently marketed reagents are analyzed using this version.

*DNBelab_C_Series_scRNA-analysis-software* is a very early version, and the adapted reagent version only has one cDNA library. It is no longer in use.

**Comment by m-fayer** [comment]
Thank you so much for the clarification!

**Comment by m-fayer** [comment]
Thank you so much for the clarification!
