### ISSUE TITLE
When Oligo reads are unavailable

### ISSUE THREAD

**Issue by m-fayer** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#29]
Hi, our sequencing procedure had some problem and oligo reads for some samples are not available. In terms of biology, we should be able to leave the Oligo library and still get useful data. Is there any way to bypass the oligo library or use [the older tool](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_scRNA-analysis-software)? Thanks a lot.

**Comment by lishuangshuang0616** [comment]
You can find oligo data that is not the sample, and try to keep the number of sequences relatively small (but it must be greater than 100,000 reads) so that the process can be analyzed. This results in an expression matrix without magnetic bead merging. @m-fayer
