### ISSUE TITLE
s1.get.similarityOfBeads: main.c:392: collect_bead_infos: Assertion `((infos)->n) > 0' failed.

### ISSUE THREAD

**Issue by HengkuanLi** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#3]
[<0x1b>[38;5;1merror<0x1b>[0m] WorkflowManagerActor Workflow b86d7759-6bf5-433b-a438-5ad954cc4963 failed (during ExecutingWorkflowState): Job main.getM280UMI:NA:1 exited with return code 134 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.

s1.get.similarityOfBeads: main.c:392: collect_bead_infos: Assertion `((infos)->n) > 0' failed.
*/cromwell-executions/main/b86d7759-6bf5-433b-a438-5ad954cc4963/call-getM280UMI/execution/script: line 34: 39666 Aborted

**Comment by lishuangshuang0616** [comment]
s1.get.similarityOfBeads: main.c:392: collect_bead_infos: Assertion `((infos)->n) > 0' failed.，可以查看下02.count/*_CB_UB_count.txt这个文件是否为空。如果为空或者文件行数很少，可能是oligo文库没有识别到oligo barcode（如果cDNA文库和oligo文库混合测序且暗反应按照cDNA文库测序方法，则需要对oligo文库的R2端进行切割），wdl流程将main.OligoBarcode替换成*/DNBC4tools/config/DNBelabC4_scRNA_oligomix_readStructure.json，命令行的话增加—mixseq参数。可以参考说明文件中的FAQ。
