### ISSUE TITLE
使用final.bam文件运行velocyto

### ISSUE THREAD

**Issue by Xixu551** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#32]
我想要运行velocyto，而华大仅返回了fastq文件和final.bam文件(约60GB），当我运行如下命令：
```
velocyto run --bcfile /home/chenzhizhuo/Data/keloid/ActK6/barcodes.tsv.gz --outputfolder ./velocyte/ActK6 /home/chenzhizhuo/Data/keloid/ActK6/final.bam /home/chenzhizhuo/refdata-gex-GRCh38-2020-A/genes/genes.gtf
```
出现了如下报错：
```
[E::idx_find_and_load] Could not retrieve index file for '/home/chenzhizhuo/Data/keloid/ActK6/final.bam'
```

**Comment by lishuangshuang0616** [comment]
I'm not sure about the contents of the returned final.bam file. 
Judging from your error report, you need to build an index for final.bam and use `samtools index`.
 If your final.bam is not sorted, you have to use `samtools sort` to sort.

**Comment by Xixu551** [comment]
> I'm not sure about the contents of the returned final.bam file. Judging from your error report, you need to build an index for final.bam and use `samtools index`. If your final.bam is not sorted, you have to use `samtools sort` to sort.

Is there any arguments to let velocyto identify .bai file from 'samtools index'?

**Comment by lishuangshuang0616** [comment]
Sorry, only need `samtools sort`

**Comment by Xixu551** [comment]
> Sorry, only need `samtools sort`

I notice that the RNA velocity matrix in output directory has the following structure:
`antisense.mtx.gz  features.tsv.gz  spliced.mtx.gz
barcodes.tsv.gz   spanning.mtx.gz  unspliced.mtx.gz`
Is there any thing I can do to convert it to .loom files so that it can be compatible with Scvelo's or Velocyto's python implemention?

**Comment by yangyiling10** [comment]
我也有这个问题，请问您解决了吗
