### ISSUE TITLE
生成的报告中有两个图中的文字不能显示

### ISSUE THREAD

**Issue by Kellytian124** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#33]
![cf556c07a44325dac06bf31460672da](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/76393047/477e4434-3553-4527-ae16-79701a30f7f5)
请问这个问题该怎么解决呢？

**Comment by Kellytian124** [comment]
运行方式为
singularity exec dnbc4tools_v2.1.sif dnbc4tools atac run

**Comment by lishuangshuang0616** [comment]
能看下分析的输出报告信息吗？这块的信息，一直包含到结尾
```
Computing hash
Checking for 9562 cell barcodes
Extracting reads overlapping genomic regions
NULL
Warning: Keys should be one or more alphanumeric characters followed by an underscore, setting key from peaks to peaks_
Finding + strand cut sites
Finding - strand cut sites
Computing mean insertion frequency in flanking regions
Normalizing TSS score
Performing TF-IDF normalization
Running SVD
Scaling cell embeddings
..........
..........
..........
```

**Comment by Kellytian124** [comment]
Computing hash
Checking for 11632 cell barcodes
Extracting reads overlapping genomic regions
Warning: Keys should be one or more alphanumeric characters followed by an underscore, setting key from peaks to peaks_
Finding + strand cut sites
Finding - strand cut sites
Computing mean insertion frequency in flanking regions
Normalizing TSS score
Performing TF-IDF normalization
Running SVD
Scaling cell embeddings
Warning: The default method for RunUMAP has changed from calling Python UMAP via reticulate to the R-native UWOT using the cosine metric
To use Python UMAP via reticulate, set umap.method to 'umap-learn' and metric to 'correlation'
This message will be shown once per session
11:11:36 UMAP embedding parameters a = 0.9922 b = 1.112
11:11:36 Read 11287 rows and found 30 numeric columns
11:11:36 Using Annoy for neighbor search, n_neighbors = 30
11:11:36 Building Annoy index with metric = cosine, n_trees = 50
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
11:11:37 Writing NN index file to temp file /tmp/624670.1.sk.q/RtmpRGjPZl/filedf6e93ee6a2ac
11:11:37 Searching Annoy index using 4 threads, search_k = 3000
11:11:38 Annoy recall = 100%
11:11:41 Commencing smooth kNN distance calibration using 4 threads with target n_neighbors = 30
11:11:45 Initializing from normalized Laplacian + noise (using irlba)
11:11:45 Commencing optimization for 200 epochs, with 469790 positive edges
Using method 'umap'
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
11:11:51 Optimization finished
Computing nearest neighbor graph
Computing SNN

是这样的。

**Comment by lishuangshuang0616** [comment]
嗯嗯，目前来看容器版本有时候会出现这么问题，我这边正在修复这个问题，下个版本修复。
非常抱歉

**Comment by Kellytian124** [comment]
嗯嗯明白了，谢谢你的回复

**Comment by lishuangshuang0616** [comment]
> 嗯嗯明白了，谢谢你的回复

您好，可更新新的版本dnbc4tools_v2.1.1来解决这个问题。 @Kellytian124
