### ISSUE TITLE
ATAC demo data

### ISSUE THREAD

**Issue by m-fayer** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#35]
Hi,

Do you have any ATAC demo data to test the pipeline's scATAC command? Thanks in advance.

**Comment by lishuangshuang0616** [comment]
https://db.cngb.org/search/project/CNP0004369, the two fastq datas are from the same sample.
Mouse Brain ATAC demo data. @m-fayer 
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/49019821/639caf88-7f79-40ec-b5d1-ae95cf5ed6ec)

**Comment by m-fayer** [comment]
Thank you so much!
