### ISSUE TITLE
报告中显示的细胞数量和doublets_info.txt中的细胞数相差很多

### ISSUE THREAD

**Issue by antecede** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#37]
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/46232487/464a038b-997d-486d-a6b6-1c450654e1e9)
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/46232487/ffa8d16b-79ce-49a4-8a42-784644524cca)
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/46232487/89e50a93-d894-4f66-b1a8-1ec6aa160ea8)

请教一下开发团队如下问题：

第一幅图中的绿色是否为Singlet？
另外filter_matrix得到的数量和第一幅图中细胞总数一致，也就是说未进行空液滴和一个油包水多个细胞情况的去除？但是流程中有相关的操作步骤的呀，第三幅图灰色部分不就是算的空液滴这些吗？为何利用seurat读取filter_matrix得到的细胞总数还是第一幅图的那个细胞数量呢？

盼望回复，感谢开发团队的辛勤付出！

**Comment by antecede** [comment]
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/46232487/c3de4372-012a-4e9a-94e9-57d800246938)
另外一个比较明显的问题：

流程中得到的所有样本的网页报告中总细胞量都远远高于当初湿实验投入的细胞量，由于细胞捕获率可能也就50%左右，流程跑完得到的细胞量理论上应该比湿实验投入的细胞量少吧，怎么反而会多这么多呢？

盼望回复，感谢开发团队的辛勤付出！

**Comment by lishuangshuang0616** [comment]
您好，第一幅图并不是鉴定的双胞。这是C4分析得到的液滴内beads的分布，绿色为该液滴内有1个磁珠，橙色是两个磁珠。多个磁珠需要将捕获到的umi进行合并。第一幅图的细胞数量就是filter_matrix的细胞数量。
细胞数量大于投入数量可能的原因是计数的准确性以及背景污染导致的细胞数量不准确。
有个小的建议，您的分析软件版本可以更新到最新的2.1.1版本。
@antecede 
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/49019821/1755a4f3-422a-42c7-b247-23385be344c6)

**Comment by antecede** [comment]
@lishuangshuang0616 感谢您的及时回复！

- 这部分数据是我在2.1.0版本下得到的，数据全部跑完可能需要一个月时间，目前下游分析已经全做完了。您预计2.1.1版本的更新对下游分析得到的结果会有多大的影响呢？

- filter_matrix得到的结果是去除双胞的吗？因为我在结果中间文件中看到了鉴定双胞的运算文件，细胞数量和报告中返回的差距很大。如下图所示
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/46232487/502e0d0e-492a-450e-aaf8-29a47220c201)

- `细胞数量大于投入数量可能的原因是计数的准确性以及背景污染导致的细胞数量不准确。`您这里说的是湿实验部分的计数不准确和背景污染吗？所以最后细胞数量的精确计数应以生信分析得到的结果为准是吗？可是听销售说一个建库最多只能测到8千个细胞左右，这里一个建库就得到了5.2万个细胞，可能的原因是什么呢？

**Comment by lishuangshuang0616** [comment]
1. 在2.1.1版本中，我们优化了磁珠合并部分。应该会有更多的磁珠合并。如果已经使用2.1.0分析完成可不用更新。
2. filter_matrix没有去除双胞。结果中包括cell calling得到的全部细胞。后续的去除双胞是用于聚类展示，不影响filter_matrix。doublets_info.txt这个文件应该是2.0.7版本和之前的，展示的数据是doublefinder鉴定的双胞以及通过gene数和线粒体过滤后的细胞数量，是filter_matrix之后的操作，不影响filter_matrix。
3. 单细胞液滴系统投入细胞数量越多会带来双胞污染的问题，所以投入细胞是有一个建议值。您的结果来看似乎是存在背景的污染。可以在下游分析中进行过滤下。

**Comment by antecede** [comment]
@lishuangshuang0616 非常感谢您的耐心且及时的回复！我还有如下问题，盼望得到您的耐心解答：

1. 您这里提到的背景污染是指**环境RNA污染**吗？您提到的**下游分析**中过滤是指利用`SoupX`等软件去除这种污染吗？
2. 如果是**2.0.7**下跑的结果您是否还建议用**2.1.1**重新再跑一遍。您提到`doublets_info.txt这个文件应该是2.0.7版本和之前的`应该是后来更新了软件导致我那天查看版本时候显示2.1.0，但是我的结果应该还是在**2.0.7**之前得到的，因为当时参考的如下说明文档（它的最新版本还只是2.0.7，不知道这个**系统**的说明文档是否还有更新的计划，2.1.1下运行需要微调命令了）
`https://dnbc4tools.readthedocs.io/zh/latest/analysis.html`
3. 请问`[DNBelab_C_Series_scRNA-analysis-software](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_scRNA-analysis-software)`和当前仓库（**high-throughput DNBelab C Series single-cell RNA**）有试剂盒适用范围吗？即哪些平台或者试剂盒必须用哪套流程，我看非HT流程更新日期停留在去年了，而且流程图等做工细致方面也不如当前流程美观用心。

**Comment by lishuangshuang0616** [comment]
1.可能是细胞破损导致背景环境中的umi比较高，自动获取到的细胞可能不准确，可以在下游根据基因数量和线粒体去过滤掉部分的细胞。
2.这个文档暂时还没有更新计划。针对这种捕获细胞很多的样本，可以测试一两个看下结果是否有改善。
3.DNBelab_C_Series_scRNA-analysis-software这个软件版本对应的试剂是低通量版本并未上市，可不用关注。

**Comment by antecede** [comment]
@lishuangshuang0616 非常感谢您详实且耐心的解答！
