### ISSUE TITLE
<0x1b>[31m[error] [func: write_outs, line: 450] <0x1b>[0m<0x1b>[35mNo barcode found.<0x1b>[0m

### ISSUE THREAD

**Issue by HengkuanLi** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#4]
[2022-08-10 22:14:28,80] [<0x1b>[38;5;1merror<0x1b>[0m] WorkflowManagerActor Workflow 89b563a4-cb75-4edb-ac7f-141616788c21 failed (during ExecutingWorkflowState): Job main.cDNAanno:NA:1 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.
Check the content of stderr for potential additional information: /work/home/aclwpl64n0/shanhuiquan/chicken/cromwell-executions/main/89b563a4-cb75-4edb-ac7f-141616788c21/call-cDNAanno/execution/stderr.
 [31m[error] [func: write_outs, line: 450] [0m[35mNo barcode found.[0m

**Comment by lishuangshuang0616** [comment]
In version2.0.0, the gene line of the gtf file needs to have gene_name and gene_id, and other lines need to include gene_name, gene_id, transcript_name and transcript_id, otherwise the genes cannot be annotated. This error means that the gene is not annotated, you can view the file “anno_report.csv”. The gtf file needs to be adjusted as required.

**Comment by HengkuanLi** [comment]
好的，非常感谢您




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月13日(星期六) 中午1:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software] <0x1b&gt;[31m[error] [func: write_outs, line: 450] <0x1b&gt;[0m<0x1b&gt;[35mNo barcode found.<0x1b&gt;[0m (Issue #4)





 
In version2.0.0, the gene line of the gtf file needs to have gene_name and gene_id, and other lines need to include gene_name, gene_id, transcript_name and transcript_id, otherwise the genes cannot be annotated. This error means that the gene is not annotated, you can view the file “anno_report.csv”. The gtf file needs to be adjusted as required.
