### ISSUE TITLE
Error in loadNamespace(x) : there is no package called ‘argparse’

### ISSUE THREAD

**Issue by uddamvathanak** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#40]
2023-11-23 02:38:44
Generating the raw expression matrix.
2023-11-23 02:47:09,736 - count - ERROR
Command failed with exit code 1
2023-11-23 02:47:09,737 - count - ERROR
Error in loadNamespace(x) : there is no package called ‘argparse’
Calls: loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted

2023-11-23 02:47:09
Generating the filtered expression matrix.
2023-11-23 02:47:09,762 - count - ERROR
Command failed with exit code 1
2023-11-23 02:47:09,762 - count - ERROR
[error] [func: dict_read, line: 212] /disco_500t/rom/Colab/K0_control_processed/02.count/beads_barcodes.txt : No such file or directory.

**Comment by lishuangshuang0616** [comment]
The error message suggests that the R package argparse is not installed. To resolve this, you can run the following commands in the dnbc4tools environment:

```
conda activate dnbc4tools
conda install r-argparse
```

To re-run the dnbc4tools rna run, you only need to reanalyze the broken part, u can add the parameters --process count,analysis,report.

**Comment by uddamvathanak** [comment]
Thank you so much. So the reason I'm having this issue is that the installation process is not suitable for Miniforge installation and so I need to reinstall everything from scratch and debug by the error message. If possible please have the miniforge version of Conda. I'm from SIgN and need to run the pipeline for processing the data.

**Comment by lishuangshuang0616** [comment]
Thank you for reminding me about the Miniforge installation requirements. I will consider it.
