### ISSUE TITLE
技术老师您好，请问当每个样品有两对儿fq测序数据时，要怎么输入到dnbc4tools呢？

### ISSUE THREAD

**Issue by tyyl622** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#42]
技术老师您好，我发现我每个样品的下机数据都有两对儿fq.gz文件，如图
![P1](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/33093996/aa4f8a53-d43e-4805-b24d-590acc06b847)
但是dnbc4tools的输入是一对儿cDNAfastq：
`$dnbc4tools rna run --cDNAfastq1 /test/data/test_cDNA_R1.fastq.gz --cDNAfastq2 /test/data/test_cDNA_R2.fastq.gz
......`

这种情况我该怎么输入呢？谢谢老师救我狗命！

**Comment by lishuangshuang0616** [comment]
$dnbc4tools rna run --cDNAfastq1 FP270003949_L01_67_1.fq.gz,FP270003950_L01_67_1.fq.gz  --cDNAfastq2 FP270003949_L01_67_2.fq.gz,FP270003950_L01_67_2.fq.gz .....

**Comment by tyyl622** [comment]
Thanks very much my lady!
