### ISSUE TITLE
final.bam convert to fastq file

### ISSUE THREAD

**Issue by JackLu66** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#46]
Hello,
I have a final.bam file, and i want to convert bam file back to the paired raw fastq file. So that i can re map agin.
I try to use samtools fastq, but it can not output paired fq file correctly. Further, i tried software bamtofastq, and it is useful to convert bam to fastq file in 10X scRNA-seq data. but it is fail to convert bam file generated by DNBelab_C platform.
how can i do that in DNBelab_C platform.  looking forward to your reply.
thank you!

**Comment by lishuangshuang0616** [comment]
Sorry, we don't have that feature yet. We discard reads that do not align and their quality scores when generating the BAM file. Fully restoring the raw reads is currently not feasible. @Gordonlu66

**Comment by lishuangshuang0616** [comment]
https://github.com/shiquan/PISA
Use the PISA command PISA bam2fq to convert to single-ended  @Gordonlu66 
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/49019821/63284056-6c05-422e-81cb-5fb5df4503c9)
