### ISSUE TITLE
bioconda::bioconductor-genomeinfodbdata-1.2.9-r42hdfd78af_0 problems

### ISSUE THREAD

**Issue by Quianter** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#47]
hi MGI:
     Hi, I'm trying to install DNBC4tools2.1.1 in my linux account, but an error occurs during conda environment create:
In particualar this is the report:
message:
post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.9-r42hdfd78af_0
location of failed script: /hpcnfs/home/ieo5212/miniconda3/envs/R_single_cell1/bin/.bioconductor-genomeinfodbdata-post-link.sh
==> script messages <==

==> script output <==
stdout: /hpcnfs/home/ieo5212/miniconda3/envs/R_single_cell1/share/genomeinfodbdata-1.2.9/"GenomeInfoDbData_1.2.9.tar.gz": OK
ERROR: sub-architecture 'R' is not installed
ERROR: sub-architecture 'R.c~' is not installed

stderr: ++ dirname -- /hpcnfs/home/ieo5212/miniconda3/envs/R_single_cell1/bin/installBiocDataPackage.sh

SCRIPT_DIR=/hpcnfs/home/ieo5212/miniconda3/envs/R_single_cell1/bin/../share/bioconductor-data-packages
json=/hpcnfs/home/ieo5212/miniconda3/envs/R_single_cell1/bin/../share/bioconductor-data-packages/dataURLs.json
++ yq '."genomeinfodbdata-1.2.9".fn' /hpcnfs/home/ieo5212/miniconda3/envs/R_single_cell1/bin/../share/bioconductor-data-packages/dataURLs.json
FN='"GenomeInfoDbData_1.2.9.tar.gz"'
IFS=
read -r value
++ yq '."genomeinfodbdata-1.2.9".urls[]' /hpcnfs/home/ieo5212/miniconda3/envs/R_single_cell1/bin/../share/bioconductor-data-packages/dataURLs.json
URLS+=($value)
IFS=
read -r value
URLS+=($value)
IFS=
read -r value
URLS+=($value)
IFS=
read -r value
++ yq '."genomeinfodbdata-1.2.9".md5' /hpcnfs/home/ieo5212/miniconda3/envs/R_single_cell1/bin/../share/bioconductor-data-packages/dataURLs.json
MD5='"7cc138cfb74665fdfa8d1c244eac4879"'
STAGING=/hpcnfs/home/ieo5212/miniconda3/envs/R_single_cell1/share/genomeinfodbdata-1.2.9
mkdir -p /hpcnfs/home/ieo5212/miniconda3/envs/R_single_cell1/share/genomeinfodbdata-1.2.9
TARBALL='/hpcnfs/home/ieo5212/miniconda3/envs/R_single_cell1/share/genomeinfodbdata-1.2.9/"GenomeInfoDbData_1.2.9.tar.gz"'
SUCCESS=0
for URL in '${URLS[@]}'
++ echo '"https://bioconductor.org/packages/3.16/data/annotation/src/contrib/GenomeInfoDbData_1.2.9.tar.gz"'
++ tr -d '"'
URL=https://bioconductor.org/packages/3.16/data/annotation/src/contrib/GenomeInfoDbData_1.2.9.tar.gz
++ echo '"7cc138cfb74665fdfa8d1c244eac4879"'
++ tr -d '"'
MD5=7cc138cfb74665fdfa8d1c244eac4879
curl -L https://bioconductor.org/packages/3.16/data/annotation/src/contrib/GenomeInfoDbData_1.2.9.tar.gz
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
100 11.1M 100 11.1M 0 0 7708k 0 0:00:01 0:00:01 --:--:-- 7705k
[[ 0 == 0 ]]
++ uname -s
[[ Linux == \L\i\n\u\x ]]
md5sum -c
SUCCESS=1
break
[[ 1 != 1 ]]
R CMD INSTALL --library=/hpcnfs/home/ieo5212/miniconda3/envs/R_single_cell1/lib/R/library '/hpcnfs/home/ieo5212/miniconda3/envs/R_single_cell1/share/genomeinfodbdata-1.2.9/"GenomeInfoDbData_1.2.9.tar.gz"'
installing source package ‘GenomeInfoDbData’ ...
** using staged installation
** data
** inst
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - R
*** arch - R.c~
ERROR: loading failed for ‘R’, ‘R.c~’
removing ‘/hpcnfs/home/ieo5212/miniconda3/envs/R_single_cell1/lib/R/library/GenomeInfoDbData’
restoring previous ‘/hpcnfs/home/ieo5212/miniconda3/envs/R_single_cell1/lib/R/library/GenomeInfoDbData’
return code: 1

kwargs:
{}

class: LinkError
message:
post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.9-r42hdfd78af_0
location of failed script: /hpcnfs/home/ieo5212/miniconda3/envs/R_single_cell1/bin/.bioconductor-genomeinfodbdata-post-link.sh
==> script messages <==

==> script output <==
stdout: /hpcnfs/home/ieo5212/miniconda3/envs/R_single_cell1/share/genomeinfodbdata-1.2.9/"GenomeInfoDbData_1.2.9.tar.gz": OK
ERROR: sub-architecture 'R' is not installed
ERROR: sub-architecture 'R.c~' is not installed

stderr: ++ dirname -- /hpcnfs/home/ieo5212/miniconda3/envs/R_single_cell1/bin/installBiocDataPackage.sh

SCRIPT_DIR=/hpcnfs/home/ieo5212/miniconda3/envs/R_single_cell1/bin/../share/bioconductor-data-packages
json=/hpcnfs/home/ieo5212/miniconda3/envs/R_single_cell1/bin/../share/bioconductor-data-packages/dataURLs.json
++ yq '."genomeinfodbdata-1.2.9".fn' /hpcnfs/home/ieo5212/miniconda3/envs/R_single_cell1/bin/../share/bioconductor-data-packages/dataURLs.json
FN='"GenomeInfoDbData_1.2.9.tar.gz"'
IFS=
read -r value
++ yq '."genomeinfodbdata-1.2.9".urls[]' /hpcnfs/home/ieo5212/miniconda3/envs/R_single_cell1/bin/../share/bioconductor-data-packages/dataURLs.json
URLS+=($value)
IFS=
read -r value
URLS+=($value)
IFS=
read -r value
URLS+=($value)
IFS=
read -r value
++ yq '."genomeinfodbdata-1.2.9".md5' /hpcnfs/home/ieo5212/miniconda3/envs/R_single_cell1/bin/../share/bioconductor-data-packages/dataURLs.json
MD5='"7cc138cfb74665fdfa8d1c244eac4879"'
STAGING=/hpcnfs/home/ieo5212/miniconda3/envs/R_single_cell1/share/genomeinfodbdata-1.2.9
mkdir -p /hpcnfs/home/ieo5212/miniconda3/envs/R_single_cell1/share/genomeinfodbdata-1.2.9
TARBALL='/hpcnfs/home/ieo5212/miniconda3/envs/R_single_cell1/share/genomeinfodbdata-1.2.9/"GenomeInfoDbData_1.2.9.tar.gz"'
SUCCESS=0
for URL in '${URLS[@]}'
++ echo '"https://bioconductor.org/packages/3.16/data/annotation/src/contrib/GenomeInfoDbData_1.2.9.tar.gz"'
++ tr -d '"'
URL=https://bioconductor.org/packages/3.16/data/annotation/src/contrib/GenomeInfoDbData_1.2.9.tar.gz
++ echo '"7cc138cfb74665fdfa8d1c244eac4879"'
++ tr -d '"'
MD5=7cc138cfb74665fdfa8d1c244eac4879
curl -L https://bioconductor.org/packages/3.16/data/annotation/src/contrib/GenomeInfoDbData_1.2.9.tar.gz
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
100 11.1M 100 11.1M 0 0 7708k 0 0:00:01 0:00:01 --:--:-- 7705k
[[ 0 == 0 ]]
++ uname -s
[[ Linux == \L\i\n\u\x ]]
md5sum -c
SUCCESS=1
break
[[ 1 != 1 ]]
R CMD INSTALL --library=/hpcnfs/home/ieo5212/miniconda3/envs/R_single_cell1/lib/R/library '/hpcnfs/home/ieo5212/miniconda3/envs/R_single_cell1/share/genomeinfodbdata-1.2.9/"GenomeInfoDbData_1.2.9.tar.gz"'
installing source package ‘GenomeInfoDbData’ ...
** using staged installation
** data
** inst
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - R
*** arch - R.c~
ERROR: loading failed for ‘R’, ‘R.c~’
return code: 1

ValueError: unsupported format character 'T' (0x54) at index 2255

Thanks

**Comment by lishuangshuang0616** [comment]
Can you check the R version of R_single_cell1? Is this environment a newly created environment, created using conda create dnbc4toos.yaml?

Try:
conda clean --all -y
remove the mirrors in ~/.condarc

**Comment by Quianter** [comment]
> Can you check the R version of R_single_cell1? Is this environment a newly created environment, created using conda create dnbc4toos.yaml?
> 
> Try: conda clean --all -y remove the mirrors in ~/.condarc

it is a newly created conda environment based on dnbc4toos.yaml, the intresting thing is the same conda install pipeline can complete in my another cluster server successfully.
So, does it need a specific version compiler in my base environment, like gcc or cmake?

**Comment by lishuangshuang0616** [comment]
Can it be installed successfully? @Quianter

**Comment by Quianter** [comment]
> Can it be installed successfully? @Quianter

Thanks, I had done it yesterday with creating new conda env after conda reinstall.

**Comment by shengw-c** [comment]
Had the same issue with v1.2.9, but v1.2.7 works.
