### ISSUE TITLE
华大单细胞分析工具输入数据问题

### ISSUE THREAD

**Issue by Zjianglin** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#48]
开发者您好, 我从文章和github上看到关于华大DNBelab C4单细胞测序数据分析有几种描述,主要是`PISA+STAR`和`[DNBelab_C_Series_HT_scRNA-analysis-software](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software)`,后者也就是`dnb4ctools`;还有一个`[DNBelab_C_Series_scRNA-analysis-software](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_scRNA-analysis-software)`. 这几个工具/流程的输入数据并不完全相同:
1. 参照PISA教程([Vignette1 : Generate gene count matrix for scRNA](https://github.com/shiquan/PISA/wiki/Vignette1-:-Generate-gene-count-matrix-for-scRNA)),需要准备双端测序数据(`sample.R1.fq.gz`和`sample.R1.fq.gz`)和参考基因组即可.
2. 参照`DNBelab_C_Series_HT_scRNA-analysis-software`教程(`[quick start](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/blob/version2.0/doc/quickstart.md)`),除了参考基因组,需要四个测序数据,分别是`cDNA_R1.fastq.gz`, `cDNA_R2.fastq.gz`, `oligo2_1.fq.gz`和`oligo2_2.fq.gz`.
3. `[DNBelab_C_Series_scRNA-analysis-software](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_scRNA-analysis-software)`此外这个工具也只需要双端测序数据即可.

请问一下为什么这几个流程的输入差别会比较大, 对于从数据库下载的公开数据(一般只有双端测序数据),是不是意味着只能使用`PISA+STAR`的流程,但是这个流程自己一步一步跑比较 繁琐,能否直接使用`dnbc4tools`工具,如果可以,请问应该如何运行呢?谢谢

**Comment by lishuangshuang0616** [comment]
DNBelab_C_Series_scRNA-analysis-software教程中的分析数据基于低通量试剂盒，只存在一个文库cDNA文库，DNBelab_C_Series_HT_scRNA-analysis-software基于高通量试剂盒，存在两种文库，cDNA和oligo文库。PISA教程为处理cDNA数据。如果文章中只提供了单个文库数据，无法使用dnbc4tools来分析。

**Comment by Zjianglin** [comment]
谢谢回复.那针对文献提供的只有单个样本文库的双端测序数据,使用`PISA+STAR`和`DNBelab_C_Series_scRNA-analysis-software`教程流程理论上结果是否应该是一样的呢?

**Comment by lishuangshuang0616** [comment]
是一样的，DNBelab_C_Series_scRNA-analysis-software软件很久未更新过，建议将STAR与PISA更新到文献说明的版本

**Comment by Zjianglin** [comment]
好的,那是否意味着对于DNBelab C4低通量试剂盒测序数据(仅有一个双端测序reads)的推荐使用`PISA+STAR`流程,而对于具有cDNA文库和oligo文库的高通量试剂盒测序数据(两对双端测序reads)的只能用`dnbc4tools`工具包进行预处理? 当前`dnbc4tools`确实简单方便,我只是问一下

**Comment by lishuangshuang0616** [comment]
Yes, the high-throughput version has a cell barcode merging step, and there is no way to process oligo data simply using STAR+PISA.

**Comment by Zjianglin** [comment]
Thanks for your nice reply
