### ISSUE TITLE
alignment_report.csv 统计问题

### ISSUE THREAD

**Issue by cherriyoush** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#5]
你好，输出文件alignment_report.csv中的 Raw reads和Mapped reads一样，我跑的3个样本比对率都是100%:
![image](https://user-images.githubusercontent.com/23136607/186384527-1f7c83ac-62fa-45eb-9e6a-83a650c4cc3e.png)
这个Raw reads 应该是文件Log.final.out中的行 Number of input reads的对应统计的reads数吧

**Comment by lishuangshuang0616** [comment]
可以参考html报告中的结果，alignment_report.csv中Raw Reads和Mapped reads实际都为Mapped reads（生成的bam中去除了未比对上的reads减少bam存储），真实的Raw Reads结果见cDNA_sequencing_report.csv中的Fragments pass QC。

**Comment by cherriyoush** [comment]
多谢
