### ISSUE TITLE
RUN error: count - ERROR  Command failed with exit code 134

### ISSUE THREAD

**Issue by zengh58** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#51]
Hi, I encountered some errors when running the code below:

```
dnbc4tools rna run   --cDNAfastq1 cDNAlib-A3_raw_1.fq.gz   --cDNAfastq2 cDNAlib-A3_raw_2.fq.gz   --oligofastq1 oligolib-A3_raw_1.fq.gz   --oligofastq2 oligolib-A3_raw_2.fq.gz   --genomeDir ref   --name A3 --threads 50
```
The error is depicted in the picture:
![c81211d8131de3086b37821562d1175](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/45784587/e685b04e-7c1a-484b-be95-ace874a730c3)

I noticed a similar issue reported by others. However, based on the solution provided, my "CB_UB_count.txt" file is not empty. Thus, I'm unsure about the exact problem or what steps to take next. Could you offer any guidance? Thank you!

**Comment by lishuangshuang0616** [comment]
Screenshot 01.data

**Comment by zengh58** [comment]
![444b907900e991cb64cdb92d1b17211](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/45784587/7b204f65-0ced-46f6-9833-f670e5f77e08)

**Comment by lishuangshuang0616** [comment]
ls -lh，look at the storage space of the file
and the contents of the **_alignment_report.csv_** and **_anno_report.csv_** files.

**Comment by zengh58** [comment]
01.data:
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/45784587/d1d313ee-58c0-40c0-bbb9-583c7ab92b05)

alignment_report.csv：
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/45784587/ec288b91-f325-4140-8f3a-91dacfd968b5)

anno_report.csv：
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/45784587/c2ff52ec-8bd5-4706-a3ac-d0a22be9376f)

**Comment by lishuangshuang0616** [comment]
There is something wrong with your gtf file。
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/49019821/e11ed053-b8c5-4662-b9b4-0f643aa60603)

**Comment by zengh58** [comment]
Thank you for your solution! 
I have two GTF files; this time, I used the first one. I thought it meets the conditions mentioned above. 
However, if the first one is not okay, is the other one correct? Thank you!

The first one:
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/45784587/4a1aeb51-064e-483f-9862-ca56d1a33e8b)

The other one:
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/45784587/cc1c9fca-9f2d-4eb4-aa4b-7e0e8a5810fc)

**Comment by zengh58** [comment]
Oh, I must mention that, initially, I ran the code from your tutorial:
`dnbc4tools tools mkgtf --ingtf ref.gtf --output genes.filter.gtf --type gene_type`
However, the output file _**genes.filter.gtf**_ is empty, and subsequent code failed. Consequently, I skipped that step and used the original GTF as the input for the "_**dnbc4tools rna run**_". I'm uncertain if this has any impact.

**Comment by lishuangshuang0616** [comment]
The filtering step is optional. 
The other one is OK

**Comment by zengh58** [comment]
Thank you for your help! I'll give it a try.

**Comment by zengh58** [comment]
Excuse me, I used the other GTF file, but I encountered another error...
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/45784587/5b47bedd-2b0d-402f-80d3-d61d8af652db)

**Comment by lishuangshuang0616** [comment]
Your environment is not installed properly. You can test whether the R **_library (DropletUtils)_** is installed successfully. If the installation is not successful, reinstall **_dnbc4tools_**. If there is no problem with the installation, it may be that the **_.Rprofile_** file exists in the home directory or the R-related path exists in **_~/.bashrc_**, causing the location of the identified package to be specified.
if reinstall, you can modify the mirror in yaml to ensure that the installation does not go wrong.
```
name: dnbc4tools
channels:
  - http://mirrors.bfsu.edu.cn/anaconda/pkgs/r/
  - http://mirrors.bfsu.edu.cn/anaconda/pkgs/main/
  - http://mirrors.bfsu.edu.cn/anaconda/pkgs/free/
  - http://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/
  - http://mirrors.bfsu.edu.cn/anaconda/cloud/bioconda/
  - bioconda
  - conda-forge
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/
dependencies:
```

Since you have completed the analysis of 01.data, add --process count, analysis, report when re-analyzing to skip the completed steps.

**Comment by zengh58** [comment]
Thank you! I've resolved the issue. When I tried to load **_DropletUtils_**, it prompted me about the missing **_S4Arrays_** package. After installing it, everything worked smoothly, and the code is now running fine.
