### ISSUE TITLE
scATAC-seq bam file

### ISSUE THREAD

**Issue by yc508** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#52]
老师你好，

我这边想用diffbind来做后续的分析，然后想要得到某一个cluster的bam file. 想问一下有没有可能拿到最后bam file， 然后这个bam file在最终文件夹的位置， 我目前只在output里找到了peak matrix和fragment file。

谢谢！

**Comment by lishuangshuang0616** [comment]
Because the software used in the analysis process is **_chromap_**, the bed file obtained directly is the bed file of fragments, so there is no bam file.

**Comment by yc508** [comment]
老师你好，

我后续的分析还是需要用到bam file，我看chromap的output可以提供sam file，我想问一下dnbc4tools的script里面哪里可以改参数然后把sam file也return了，我再自己进行bam file的conversion。非常感谢！

**Comment by lishuangshuang0616** [comment]
Because there will be some problems using bam in the merge step, the format of bam is not provided.
```
chromap --preset atac --bc-error-threshold 1 --trim-adapters -x  genome.index -r genome.fa -1 fastq_1.fq.gz -2 fastq_2.fq.gz --barcode fastq_1.fq.gz --barcode-whitelist /miniconda3/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/config/whitelist_atac.txt.gz --read-format bc:0:19,r1:20:-1 -t 20 -o alignment.sam --SAM 2>alignment_report.tsv
samtools view -S -b alignment.sam  > alignment.bam
samtools index alignment.bam
```
chromap can use the above command line.

**Comment by yc508** [comment]
老师你好，

谢谢你的帮助！我会用chromap尝试一下alignment的。
