### ISSUE TITLE
conda安装dnbc4tools环境报错

### ISSUE THREAD

**Issue by ZiggeyQi** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#53]
技术老师你好，我用conda env create -f dnbc4tools.yaml -n dnbc4tools配置环境时报错如下：
Collecting package metadata (repodata.json): done
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 23.7.4
  latest version: 23.11.0

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.11.0

Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(945): An error occurred while installing package 'bioconda::bioconductor-genomeinfodbdata-1.2.9-r42hdfd78af_0'.
Rolling back transaction: done

LinkError: post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.9-r42hdfd78af_0
location of failed script: /gpfs/home/qihansong/anaconda3/envs/dnbc4tools/bin/.bioconductor-genomeinfodbdata-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout:
stderr: ++ dirname -- /gpfs/home/qihansong/anaconda3/envs/dnbc4tools/bin/installBiocDataPackage.sh
+ SCRIPT_DIR=/gpfs/home/qihansong/anaconda3/envs/dnbc4tools/bin/../share/bioconductor-data-packages
+ json=/gpfs/home/qihansong/anaconda3/envs/dnbc4tools/bin/../share/bioconductor-data-packages/dataURLs.json
++ yq '."genomeinfodbdata-1.2.9".fn' /gpfs/home/qihansong/anaconda3/envs/dnbc4tools/bin/../share/bioconductor-data-packages/dataURLs.json
Traceback (most recent call last):
  File "/gpfs/home/qihansong/anaconda3/envs/dnbc4tools/bin/yq", line 10, in <module>
    sys.exit(cli())
  File "/gpfs/home/qihansong/anaconda3/envs/dnbc4tools/lib/python3.8/site-packages/yq/__init__.py", line 63, in cli
    parser = get_parser(program_name, __doc__)
  File "/gpfs/home/qihansong/anaconda3/envs/dnbc4tools/lib/python3.8/site-packages/yq/parser.py", line 56, in get_parser
    parser = Parser(**parser_args)
TypeError: __init__() got an unexpected keyword argument 'allow_abbrev'
+ FN=

return code: 1

()

更换其他dnbc4tools版本安装也是同样的报错，请问一下这个问题应该如何解决？谢谢。

**Comment by lishuangshuang0616** [comment]
尝试将dnbc4tools.yaml前面几行改成这个channel试试
```
name: dnbc4tools
channels:
  - http://mirrors.bfsu.edu.cn/anaconda/pkgs/r/
  - http://mirrors.bfsu.edu.cn/anaconda/pkgs/main/
  - http://mirrors.bfsu.edu.cn/anaconda/pkgs/free/
  - http://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/
  - http://mirrors.bfsu.edu.cn/anaconda/cloud/bioconda/
  - bioconda
  - conda-forge
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/
dependencies:
```

**Comment by ZiggeyQi** [comment]
尝试了还是不行，可能是服务器网络的原因，换了服务器能正常安装，谢谢你的回复。
