### ISSUE TITLE
运行run the main flow 报错

### ISSUE THREAD

**Issue by owo12138** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#56]
报错如下

 ------------------------------------------------
Error: Cannot find input file or dir /share/home/xiezhixing/DNBelab_C_Series_HT_scRNA-analysis-software/ref.json
 ------------------------------------------------
我看了一下上面的代码运行没有报错，为何会这样呢？

**Comment by lishuangshuang0616** [comment]
RNA分析是吗，你的--genomeDir给的目录是建库的目录吗？看下这个/share/home/xiezhixing/DNBelab_C_Series_HT_scRNA-analysis-software目录内的文件截屏

**Comment by owo12138** [comment]
已经解决了，原因是没有建库完成，该地方文件存储空间太小
