### ISSUE TITLE
how to make this pipeline suitable for TE repeats quantification in genome

### ISSUE THREAD

**Issue by HUNNNGRY** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#57]
Hi, as a user of MGI-DNBC scRNA library, currently I'm interested in quantifying TE repeats in genome, but current pipeline seem not yet support this analysis. I'm wondering if this pipeline could be adapted for TE repeats quantification in genome?

From my point of view, there are two main adaptations that needed to implement to make this pipeline suitable for TE repeats quantification:
1. Add --outFilterMultimapNmax 500 to STAR, or use STARsolo instead. 
This might be achieved by adding this parameter at this link ? ([DNBC4tools/rna/star_anno.py#L231](https://github.com/lishuangshuang0616/DNBelab_C_Series_HT_scRNA-analysis-software/blob/1944d5ae02e5921cf124a6c06be0e370991ff5f4/DNBC4tools/rna/star_anno.py#L231)) 
2. Add Expectation-Maximization Counting like this script [wanqingshao/TE_expression_in_scRNAseq/blob/master/scripts/scRNA_UMI_counting.R](https://github.com/wanqingshao/TE_expression_in_scRNAseq/blob/master/scripts/scRNA_UMI_counting.R), or other methods based on counting of region.

**Comment by lishuangshuang0616** [comment]
Thank you for your suggestion, we will carefully evaluate it.
