### ISSUE TITLE
重复性问题

### ISSUE THREAD

**Issue by cherriyoush** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#6]
你好；对于同一个样本，相同的命令行，运行了2次，得到的filter_matrix中细胞数分别是5652和5650；我追溯了raw_matrix，再到final.bam，发现是final.bam不同；请问生成final.bam的过程存在随机性嘛？

**Comment by lishuangshuang0616** [comment]
首先感谢您的反馈，我们目前已经注意到了这个问题，fibal.bam存在reads随机排列的问题（scStar多线程写入顺序的先后导致），导致raw_matrix会存在featrue和gene排序的不一致，emptydrops采用随机抽样计算p值导致两次分析存在一些差异。我们目前正在着手解决这个问题，让输出的bam的顺序按照输入fastq顺序排列，这个问题将在下个版本中得到解决。

**Comment by cherriyoush** [comment]
谢谢，解释的很清楚

**Comment by lishuangshuang0616** [comment]
目前更新了2.0.6的版本，对final.bam进行了排序，解决了结果的随机性。
