### ISSUE TITLE
DNBC4Tools产生的单细胞数据可以使用MARVEL进行RNA剪接分析吗？

### ISSUE THREAD

**Issue by TianYu-828** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#61]
你好，我想使用MARVEL对C4的单细胞RNA数据进行RNA剪接分析，但是没有合适的cell barcode list可以指定。请问有合适的解决方法吗？

**Comment by lishuangshuang0616** [comment]
You can try using **_/miniconda3/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/config/whitelist_atac.txt.gz_** for the whitelist. I haven't used this software before, so I can't give you an accurate response.

**Comment by TianYu-828** [comment]
感谢你的回复，但是我并没有在我的路径下发现这个文件。如果方便的话，可否将此文件发送到我的邮箱。leon.tianyu@hotmail.com

**Comment by TianYu-828** [comment]
非常感谢你的回复，我在2.0.7版本中没有发现这个文件，但是在2.1.1中发现了“whitelist_atac.txt.gz”。我是否需要使用2.1.1版本对下机数据重新进行分析？
能否提供适合DNBC4单细胞数据进行RNA剪接的分析软件？

**Comment by lishuangshuang0616** [comment]
不用重新分析，2.1.1版本whitelist和之前版本的一致，只是我发现这个whitelist_atac.txt.gz文件刚好适合你使用。
我并没有太多这块分析的经验，暂时不能提供帮助，抱歉。

**Comment by TianYu-828** [comment]
好的，非常感谢。

**Comment by dongwei1220** [comment]
> 非常感谢你的回复，我在2.0.7版本中没有发现这个文件，但是在2.1.1中发现了“whitelist_atac.txt.gz”。我是否需要使用2.1.1版本对下机数据重新进行分析？ 能否提供适合DNBC4单细胞数据进行RNA剪接的分析软件？

您好，你用MARVEL软件分析DNBC4单细胞数据数据成功了吗？

**Comment by lishuangshuang0616** [comment]
我没测试，你是在分析中遇到了哪块有问题吗？

**Comment by dongwei1220** [comment]
> 我没测试，你是在分析中遇到了哪块有问题吗？

我是做的5‘端测序的，想用MARVEL做可变剪切分析，在用STAR比对的时候，我们这个测序的read1只有30bp，里面那部分是cell barcode和UMI序列呀。 

![Image](https://github.com/user-attachments/assets/adcee37c-d2be-4311-bf6e-c51020cb4aba)

STAR比对的时候这两个参数soloCBposition，soloUMIposition该怎么设置呀

![Image](https://github.com/user-attachments/assets/6a73de81-f886-4007-ae56-0c5dd6178694)

**Comment by lishuangshuang0616** [comment]
https://mp.weixin.qq.com/s/Z_oKgGanHdLPaF34WIqT3w， 你参考下这个
前20bp是cell barcode， 1-10是cb1, 11-20是cb2
21-30是umi

**Comment by dongwei1220** [comment]
> [https://mp.weixin.qq.com/s/Z_oKgGanHdLPaF34WIqT3w，](https://mp.weixin.qq.com/s/Z_oKgGanHdLPaF34WIqT3w%EF%BC%8C) 你参考下这个 前20bp是cell barcode， 1-10是cb1, 11-20是cb2 21-30是umi

还是不行，跑不成功，您们可以帮忙测试下用MAVERL软件做华大5'单细胞测序做可变剪切分析吗？
