### ISSUE TITLE
dnbc4tools atac run 运行报错

### ISSUE THREAD

**Issue by Ruvic-chen** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#64]
您好，我最近在singularity上运行dnbc4tools atac run遇到了报错，希望可以得到帮助，报错信息如下：
![Screenshot 2024-04-01 093325](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/112062618/f916b1ec-87ac-4d24-bb26-7174361b34af)

**Comment by lishuangshuang0616** [comment]
Based on your data, the software cannot recognize the sequence structure. Could you please provide screenshots of the first few sequences of R1 and R2?

**Comment by Ruvic-chen** [comment]
> Based on your data, the software cannot recognize the sequence structure. Could you please provide screenshots of the first few sequences of R1 and R2?

这是R1的序列信息
![R1](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/112062618/dd5ab662-1902-4930-9c6a-2ebdd7a7fb2e)
这是R2的序列信息
![R2](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/112062618/f1fd3fa1-63eb-4929-b670-ddd66d28e4d6)

**Comment by lishuangshuang0616** [comment]
Was your data mixed with the Illumina library and used APP-D reagent?

**Comment by hullv** [comment]
hello, i meet the same error. If my data is mixed with the Illumina library and APP-D reagent is used, how should the data be processed?

**Comment by hullv** [comment]
> Was your data mixed with the Illumina library and used APP-D reagent?

hello, i meet the same error. If my data is mixed with the Illumina library and APP-D reagent is used, how should the data be processed?

**Comment by lishuangshuang0616** [comment]
The data cannot be analyzed because the cell barcode and umi sequences cannot be sequenced. @hullv

**Comment by hullv** [comment]
> The data cannot be analyzed because the cell barcode and umi sequences cannot be sequenced. @hullv
RNA cannot be analyzed? Can't ATAC be analyzed either?

**Comment by lishuangshuang0616** [comment]
scRNA has no effect and can be analyzed. 
scATAC cannot analyze. 
@hullv
