### ISSUE TITLE
Error code: SAW-A10400, get signal: 18 

### ISSUE THREAD

**Issue by Tc940417** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#65]
您好，我在运行过程中出现了这个问题，请问是什么造成的呢？
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/145305355/11287e7b-c171-423a-b4a1-ab4ae9877800)

**Comment by lishuangshuang0616** [comment]
内存超了

**Comment by Tc940417** [comment]
@lishuangshuang0616 ，好滴谢谢你。顺便问一下，gff基因注释文件转成gtf后再进行过滤数据库后生成的文件是0字节的，请问是什么问题呀？

**Comment by lishuangshuang0616** [comment]
过滤后的gtf文件截图一下前10行我看一下

**Comment by Tc940417** [comment]
@lishuangshuang0616 您好，我是使用dnbc4tools tools mkgtf --ingtf Medicago_falcata.genome.gtf --out Medicago_falcata.filter.gtf --type gene_type，这个代码，gtf文件前十行如下图
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/145305355/dffed437-33b0-43b5-bddc-d879567c25a9)
最后输出过滤后文件为0字节文件

**Comment by Tc940417** [comment]
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/145305355/aa105a2b-a35d-417c-95ee-c2e4275b7665)
这样的

**Comment by lishuangshuang0616** [comment]
mkgtf这个步骤是可选的，你的gtf似乎也没有gene_type的标注可以不用过滤。
mkgtf过滤还会读取第三列为gene的行（软件写的固定，下个版本优化），所以输出为空。
这个gtf不用过滤就行。

**Comment by Tc940417** [comment]
我这边使用不过滤的文件构建的数据库，跑完dnbc4tools，数据结果很差，很多都在基因间区，但是我用另外的同源的基因注释文件（可以过滤的）跑出来的就很好，是不是这个没办法过滤的基因注释文件不是很好？

**Comment by lishuangshuang0616** [comment]
嗯嗯，过滤gtf的基因类型不会使你的间区比例减小，相反可能会更高。
如果你的gtf结果很差，那么可能的原因之一使gtf文件注释准确性一般。

**Comment by Tc940417** [comment]
@lishuangshuang0616 
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/145305355/7151183c-63bb-4cbb-8576-3e88765ed47c)
而且会有很多这种warning！信息，非常感谢老师答疑！

**Comment by lishuangshuang0616** [comment]
应该是transcript行的gene_id与他下面的exon的gene_id不一致导致的

**Comment by Tc940417** [comment]
好的，谢谢您的解答
