### ISSUE TITLE
 Error in barcodeRanks(t(m), lower = 0.005) :   insufficient unique points for computing knee/inflection points 2024-04-24

### ISSUE THREAD

**Issue by hullv** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#69]
您好！请问我在分析snATAC时遇到如下报错，是什么原因导致的呢？应该如何解决？运行命令如下：dnbc4tools atac run --fastq1 /nfsdata/disk11/atac/rawdata/CAPC2_raw_1.fq.gz --fastq2 /nfsdata/disk11/atac/rawdata/CAPC2_raw_2.fq.gz --genomeDir /nfsdata/disk11/reference/atac/mouse --name CAPC2 --threads 25。
报错如下：
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/131571032/cf5f9aa2-9737-4883-ad2c-3b383c0fff46)

**Comment by lishuangshuang0616** [comment]
It may be that some packages were not installed when you installed the software, and your R path was not detected during analysis.

**Comment by hullv** [comment]
但是我有四个样本，用一样的命令分析，有三个没有报错，一个报错。如果是有些包没有装的话和R路径没有检测到的话应该都报错才对。请问这应该如何解释呢？

**Comment by lishuangshuang0616** [comment]
Or try the analysis again? Add --process decon, analysis, report
This error indeed shows that the R path cannot be found.

**Comment by lishuangshuang0616** [comment]
If you still get an error, you can try using a new version of the software to analyze atac. @hullv

**Comment by hullv** [comment]
抱歉回复晚了，感谢您的帮助，我已经下载了最新版本的dnbc4tools。我在分析这个样本时dnbc4tools atac run --fastq1 /nfsdata/disk11/atac/rawdata/CAPC2_raw_1.fq.gz --fastq2 /nfsdata/disk11/atac/rawdata/CAPC2_raw_2.fq.gz --genomeDir /nfsdata/disk11/reference/atac/mouse --name CAPC2 --threads 25
报错如下：
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/131571032/fe1c8d3e-3d7d-45c9-bf7d-995183dc940f)

但是我在分析另外一个样本时dnbc4tools atac run --fastq1 /nfsdata/disk11/atac/rawdata/CAHP1_raw_1.fq.gz --fastq2 /nfsdata/disk11/atac/rawdata/CAHP1_raw_2.fq.gz --genomeDir /nfsdata/disk11/reference/atac/mouse --name CAHPPPPPPP1 --threads 25 却可以正常运行。请问这个问题应该如何解决呢？
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/131571032/eb56809b-e101-4b29-ad62-3c9e53f9d4af)

**Comment by lishuangshuang0616** [comment]
是因为你的数据量非常的低吗？我看你的比对步骤非常的快就完成了，scATAC是需要保证细胞有一定的fragments数量才够完成分析，如果只是需要测试得到报告，可以调整参数--merge_cutoff和--frags_cutoff为500甚至更低。

**Comment by hullv** [comment]
是的，只是浅测了10G。但是两个样本的数据量是接近的，为什么一个能跑一个跑不了呢？请问是因为样本的质量不好吗？

**Comment by lishuangshuang0616** [comment]
嗯嗯，可以看01.data/alignment.count.tsv每个cell barcode对应的fragments数量（过滤掉线粒体和叶绿体，相同样本可能含有的线粒体占比不一样，或者背景造成干扰占用了较多的数据），软件默认使用1000以上的cell barcode做合并步骤，如果获取的cell barcode很低01.data/beads.min.frags.tsv行数很少则会导致问题。
ATAC的合并是根据cell barcode的fragments交集来判定是否为同一液滴，如果测序量低结果就不真实。
只是测试的话可以调整--merge_cutoff和--frags_cutoff为比较低的值。

**Comment by hullv** [comment]
好的，非常感谢您的回复。我会加测样本。
