### ISSUE TITLE
RNA_velocity_issues

### ISSUE THREAD

**Issue by Landau1994** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#7]
I wonder which bam to be used in for RNA_velocity analysis，thanks!

**Comment by lishuangshuang0616** [comment]
You can read the matrix of this directory ```output/attachment/RNAvelocity_matrix```
```R
ReadPISA <- function(mex_dir=NULL,
                     barcode.path = NULL,
                     feature.path = NULL,
                     matrix.path=NULL,
                     use_10X=FALSE) {
  if (is.null(mex_dir) && is.null(barcode.path)  && is.null(feature.path) &&
        is.null(matrix.path)) {
    stop("No matrix set.")
  }
  if (!is.null(mex_dir) && !file.exists(mex_dir) ) {
    stop(paste0(mex_dir, " does not exist."))
  }
  if (is.null(barcode.path)  && is.null(feature.path) && is.null(matrix.path)) {
    barcode.path <- paste0(mex_dir, "/barcodes.tsv.gz")
    feature.path <- paste0(mex_dir, "/features.tsv.gz")
    matrix.path <- paste0(mex_dir, "/matrix.mtx.gz")
  }
  spliced.path <- paste0(mex_dir, "/spliced.mtx.gz")
  unspliced.path <- paste0(mex_dir, "/unspliced.mtx.gz")
  spanning.path <- paste0(mex_dir, "/spanning.mtx.gz")

  if (!file.exists(barcode.path) || !file.exists(feature.path)) {
    stop(paste0("No expression file found at ", mex_dir))
  }

  .ReadPISA0 <- function(barcode.path, feature.path, matrix.path, use_10X) {
    mat <- Matrix::readMM(file = matrix.path)
    feature.names <- read.delim(feature.path,
                                header = FALSE,
                                stringsAsFactors = FALSE
                                )
    barcode.names <- read.delim(barcode.path,
                                header = FALSE,
                                stringsAsFactors = FALSE
                                )
    colnames(mat) <- barcode.names$V1
    if (use_10X == TRUE) {
      rownames(mat) <- make.unique(feature.names$V2)
    } else {
      rownames(mat) <- make.unique(feature.names$V1)
    }
    mat
  }
  
  if (!file.exists(spliced.path) && file.exists(matrix.path)) {
    return(.ReadPISA0(barcode.path, feature.path, matrix.path, use_10X))
  }
  mat <- list()
  cat("Load spliced matrix ...\n")
  mat$spliced <- Matrix::readMM(file = spliced.path)
  mat$spliced <- as(mat$spliced, 'dgCMatrix')
  cat("Load unspliced matrix ...\n")
  mat$unspliced <- Matrix::readMM(file = unspliced.path)
  mat$unspliced <- as(mat$unspliced, 'dgCMatrix')
  cat("Load spanning matrix ...\n")
  mat$spanning <- Matrix::readMM(file = spanning.path)
  mat$spanning <- as(mat$spanning, 'dgCMatrix')

  feature.names <- read.delim(feature.path,
                              header = FALSE,
                              stringsAsFactors = FALSE
  )
  barcode.names <- read.delim(barcode.path,
                              header = FALSE,
                              stringsAsFactors = FALSE
  )
  colnames(mat$spliced) <- barcode.names$V1
  rownames(mat$spliced) <- make.unique(feature.names$V1)
  colnames(mat$unspliced) <- barcode.names$V1
  rownames(mat$unspliced) <- make.unique(feature.names$V1)
  colnames(mat$spanning) <- barcode.names$V1
  rownames(mat$spanning) <- make.unique(feature.names$V1)
  mat
}

EC <- ReadPISA('output/attachment/RNAvelocity_matrix')
library(Seurat)
library(velocyto.R)
emat <- EC$spliced
nmat <- EC$unspliced
smat <- EC$spanning
```

**Comment by lishuangshuang0616** [comment]
The bam used for RNA velocyto is ```anno_decon_sorted.bam``` in the **output** directory, but some processing is required because the tag of the cell barcode in bam is DB. The script is [changeBamTag.py](https://github.com/lishuangshuang0616/DNBC4tools/blob/version2.0.5/scripts/changeBamTag.py), using method 
```/miniconda3/envs/DNBC4tools/bin/python changeBamTag.py --infile anno_decon_sorted.bam --outfile velocyto.bam```

**Comment by Landau1994** [comment]
> The bam used for RNA velocyto is `anno_decon_sorted.bam` in the **output** directory, but some processing is required because the tag of the cell barcode in bam is DB. The script is [changeBamTag.py](https://github.com/lishuangshuang0616/DNBC4tools/blob/version2.0.5/scripts/changeBamTag.py), using method `/miniconda3/envs/DNBC4tools/bin/python changeBamTag.py --infile anno_decon_sorted.bam --outfile velocyto.bam`

Thanks!

**Comment by YangLi3001** [comment]
请问为什么运行上述R代码后提示`object 'matrix.path' not found`，在RNAvelocity_matrix目录下也未发现matrix.mtx.gz文件

**Comment by lishuangshuang0616** [comment]
![screen_shot_1670508878180](https://user-images.githubusercontent.com/49019821/206468587-5e8ccad8-40c5-4c7c-9cc8-a1f9848981b5.png)
@YangLi3001  Replace with analysis path。。。

**Comment by YangLi3001** [comment]
> ![screen_shot_1670508878180](https://user-images.githubusercontent.com/49019821/206468587-5e8ccad8-40c5-4c7c-9cc8-a1f9848981b5.png) @YangLi3001 Replace with analysis path。。。

Thanks!I add the matrix path, then it works.

**Comment by zebrafishCC** [comment]
Thanks for your R and python scripts  @lishuangshuang0616 . However, I couldn't find this directory 'output/attachment/RNAvelocity_matrix' and this file 'anno_decon_sorted.bam' in my output directory name 'alignment'. I used the DNBelab_C_Series_HT_scRNA-analysis-software with version less than 2.0.0

**Comment by lishuangshuang0616** [comment]
The result directory of the old version is inconsistent with the new version, using method
/miniconda3/envs/DNBC4tools/bin/python changeBamTag.py --infile **03.M280UMI_stat/anno_decon.bam** --outfile velocityto.bam. Use velocyto to convert **velocityto.bam** to loom @zebrafishCC,  **'alignment'** directory? Can you take a screenshot of the analysis directory?

**Comment by zebrafishCC** [comment]
Thanks for your quick response! @lishuangshuang0616   Sorry, I am not familiar with how to upload a figure in github. It seems like that there is no direct way to upload figures. Basically, my "alignment" directory has 7 sub-directories, i.e. '00.log', '01.DataStat', '02.cDNAAnno', '03.M280UMI_stat', '04.Matrix', '05.QCCluster', '07.report', 'symbol'.

Your collegue Dr Zhihua Li said my version of BGI-DNBelab software was old, version larger than 2.0.0 should generate necessary output directories. However, all my previous gene-matrixes and lots of downstream analysis (more than 25 samples) were performed using the old version, re-running the whole analysis with the new version of DNBelab software would be a nightmare. 

 Is it possible to perform the scVelocity analysis with the old 'final.sorted.bam' file in directory '02.cDNAAnno' by replacing the 'CB' to corresponding 'cell-ID' (for example, CELL1000_N1) in file  'sample_barcodeTranslate.txt' of '03.M280UMI_stat' directory? The 'final.sorted.bam' file after name conversion should be like those bam files generated by CellRanger of 10x genomics?

**Comment by lishuangshuang0616** [comment]
03.M280UMI_stat目录下的anno_decon.bam已经有cell-ID信息了，在DB那列，只需要按照这个方法转化一下就行
![image](https://user-images.githubusercontent.com/49019821/218091257-72068e7f-c328-4a14-b83a-175acbe67b39.png)

**Comment by zebrafishCC** [comment]
好的，谢谢你！我试试看

2023-02-10 20:21:19lishuangshuang0616 ***@***.***>写道：

03.M280UMI_stat目录下的anno_decon.bam已经有cell-ID信息了，在DB那列，只需要按照这个方法转化一下就行

**Comment by Xixu551** [comment]
> You can read the matrix of this directory `output/attachment/RNAvelocity_matrix`
> 
> ```r
> ReadPISA <- function(mex_dir=NULL,
>                      barcode.path = NULL,
>                      feature.path = NULL,
>                      matrix.path=NULL,
>                      use_10X=FALSE) {
>   if (is.null(mex_dir) && is.null(barcode.path)  && is.null(feature.path) &&
>         is.null(matrix.path)) {
>     stop("No matrix set.")
>   }
>   if (!is.null(mex_dir) && !file.exists(mex_dir) ) {
>     stop(paste0(mex_dir, " does not exist."))
>   }
>   if (is.null(barcode.path)  && is.null(feature.path) && is.null(matrix.path)) {
>     barcode.path <- paste0(mex_dir, "/barcodes.tsv.gz")
>     feature.path <- paste0(mex_dir, "/features.tsv.gz")
>     matrix.path <- paste0(mex_dir, "/matrix.mtx.gz")
>   }
>   spliced.path <- paste0(mex_dir, "/spliced.mtx.gz")
>   unspliced.path <- paste0(mex_dir, "/unspliced.mtx.gz")
>   spanning.path <- paste0(mex_dir, "/spanning.mtx.gz")
> 
>   if (!file.exists(barcode.path) || !file.exists(feature.path)) {
>     stop(paste0("No expression file found at ", mex_dir))
>   }
> 
>   .ReadPISA0 <- function(barcode.path, feature.path, matrix.path, use_10X) {
>     mat <- Matrix::readMM(file = matrix.path)
>     feature.names <- read.delim(feature.path,
>                                 header = FALSE,
>                                 stringsAsFactors = FALSE
>                                 )
>     barcode.names <- read.delim(barcode.path,
>                                 header = FALSE,
>                                 stringsAsFactors = FALSE
>                                 )
>     colnames(mat) <- barcode.names$V1
>     if (use_10X == TRUE) {
>       rownames(mat) <- make.unique(feature.names$V2)
>     } else {
>       rownames(mat) <- make.unique(feature.names$V1)
>     }
>     mat
>   }
>   
>   if (!file.exists(spliced.path) && file.exists(matrix.path)) {
>     return(.ReadPISA0(barcode.path, feature.path, matrix.path, use_10X))
>   }
>   mat <- list()
>   cat("Load spliced matrix ...\n")
>   mat$spliced <- Matrix::readMM(file = spliced.path)
>   mat$spliced <- as(mat$spliced, 'dgCMatrix')
>   cat("Load unspliced matrix ...\n")
>   mat$unspliced <- Matrix::readMM(file = unspliced.path)
>   mat$unspliced <- as(mat$unspliced, 'dgCMatrix')
>   cat("Load spanning matrix ...\n")
>   mat$spanning <- Matrix::readMM(file = spanning.path)
>   mat$spanning <- as(mat$spanning, 'dgCMatrix')
> 
>   feature.names <- read.delim(feature.path,
>                               header = FALSE,
>                               stringsAsFactors = FALSE
>   )
>   barcode.names <- read.delim(barcode.path,
>                               header = FALSE,
>                               stringsAsFactors = FALSE
>   )
>   colnames(mat$spliced) <- barcode.names$V1
>   rownames(mat$spliced) <- make.unique(feature.names$V1)
>   colnames(mat$unspliced) <- barcode.names$V1
>   rownames(mat$unspliced) <- make.unique(feature.names$V1)
>   colnames(mat$spanning) <- barcode.names$V1
>   rownames(mat$spanning) <- make.unique(feature.names$V1)
>   mat
> }
> 
> EC <- ReadPISA('output/attachment/RNAvelocity_matrix')
> library(Seurat)
> library(velocyto.R)
> emat <- EC$spliced
> nmat <- EC$unspliced
> smat <- EC$spanning
> ```

I wonder is there any recommended pipeline for Scvelo? Thanks!

**Comment by lishuangshuang0616** [comment]
Use velocyto to generate loom, and then use Scvelo for analysis @Xixu551

**Comment by yc508** [comment]
老师你好，我想使用/miniconda3/envs/DNBC4tools/bin/python changeBamTag.py --infile anno_decon_sorted.bam --outfile velocyto.bam 这个方法去替换DB 但是提示我找不到changeBamTag.py这个文件。我有试过直接用samtools去替换DB成为CB然后把原来的CB改成其他的名称，但velocyto也还是不能运行，我换完以后的bamfile长这样。请问有没有什么方法可以解决呢？谢谢！
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/96790059/8df1e616-07c2-4dd4-9d21-f55f3da25100)

**Comment by lishuangshuang0616** [comment]
可以看下报错信息吗？
