### ISSUE TITLE
RNA velocity分析

### ISSUE THREAD

**Issue by tyyl622** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#71]
请问技术老师，如何使用RNAvelocity_matrix文件夹中的内容，创建Velocyto.R分析所需的loom文件呢？
本来我想自己跑velocyto run命令，但发现找不到能用的bam文件....所以只能请教技术老师~

**Comment by lishuangshuang0616** [comment]
Is there no ***anno_decon_sorted.bam*** file in the output directory?

**Comment by tyyl622** [comment]
> Is there no _**anno_decon_sorted.bam**_ file in the output directory?

有，但是使用RNAvelocity_matrix文件夹里的barcodes文件和这个bam文件去跑velocyto run，会报错，提示bam文件中没有对应的barcode。

**Comment by lishuangshuang0616** [comment]
#67 Refer to this, bam needs to be processed

**Comment by tyyl622** [comment]
> #67 Refer to this, bam needs to be processed

好的，谢谢老师，我试一下

**Comment by tyyl622** [comment]
> #67 Refer to this, bam needs to be processed

可以了，谢谢老师，都怪我没仔细翻看以往的issues...给您添麻烦了！

**Comment by lishuangshuang0616** [comment]
Due to the bead merging in C4, the default CB is the cell barcode before merging, and the cell ID after merging is DB. However, the parameter in Velocyto is fixed as CB, so adjustment is needed. 
Feel free to ask if you have any questions. :smile:
