### ISSUE TITLE
Saturation problem

### ISSUE THREAD

**Issue by hullv** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#73]
您好！
我在计算饱和度时，检测到的基因数还是不少的，但是饱和度却很低。请问，这是什么原因引起的？新版本的软件算法是否跟之前的有不同呢。

![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/131571032/6c0ff71e-9abe-4d83-903e-c3e327fc744d)

**Comment by lishuangshuang0616** [comment]
The saturation calculation was not adjusted, and the transcript expression levels in different tissue samples varied greatly. It can be judged based on the saturation curve.

**Comment by hullv** [comment]
我用的都是小鼠的脑组织，但是我用了不同版本的试剂盒。V2版本的饱和度是正常的，V3却非常低，但是二者检测到的基因数却差不多，请问这是什么原因导致的呢？
V2↓
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/131571032/b3938788-aedc-47f2-bc96-b48c8f1ecc78)
<img width="226" alt="7a3abad362dbf696e169a08ab81fcaa" src="https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/131571032/7f3bd314-4450-4fa6-bcdb-5043c71ce3d9">

V3↓
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/131571032/deed072b-dd7e-4025-9896-65969d78b238)
<img width="227" alt="de4647145cc92a5a8d54b63c776d31c" src="https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/131571032/fb998470-9881-49b4-ac5e-ddb69df215a7">

**Comment by lishuangshuang0616** [comment]
Because the transcript capture ability of V3 to the cell nucleus is much higher than that of V2. The transcript expression level in mouse brain nucleus samples is usually relatively high, and this saturation is normal.

**Comment by hullv** [comment]
感谢您的回复。之前使用V2的时候，我们一般是根据饱和度来判断文库是否需要加测（小于70%）。请问如何判断使用V3试剂盒的样本是否需要加测呢？或者说V3的饱和度的标准应该是多少是比较合理的呢？

**Comment by lishuangshuang0616** [comment]
If your goal is to cluster cells for downstream analysis, detecting every unique transcript (UMI count) in each cell may not be necessary, and lower sequencing saturation may suffice. However, if you aim to recover very lowly expressed transcripts, higher sequencing saturation may be necessary to detect them.

**Comment by hullv** [comment]
请问对于这两种目标的饱和度，你们有推荐的范围吗？

**Comment by lishuangshuang0616** [comment]
The saturation levels vary significantly across different species and tissues. For instance, in the case of mouse brain, a relatively low number of saturated genes can achieve high values. Ultimately, the decision to perform additional testing should be based on the content of your research. If your analysis involves clustering and subsequent analytical processes, the quantity of genes should suffice for your analytical requirements.

**Comment by lishuangshuang0616** [comment]
不同的物种组织的转录本表达差异会非常大。我们对测序量达到多少饱和度没有相关的推荐范围。比如鼠脑样本，你做降维聚类，那么这么多的基因数（>1500）应该是够你的分析要求的，因为使用的是高变基因并不对一些目标基因的表达量有所要求。您可以先对数据进行分析看下能否满足自己的研究内容。

**Comment by hullv** [comment]
好的，非常感谢您的帮助！
