### ISSUE TITLE
使用PE100模式测序是否适用DNBc4tools

### ISSUE THREAD

**Issue by Tc940417** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#75]
老师您好，我的文库使用了PE100的测序模式，咱们的工具可以自动截取序列格式吗？还是需要手动截取一下，谢谢！

**Comment by lishuangshuang0616** [comment]
It can **_automatically_** trim and recognize if there is a dark reaction mode in PE100, finding the positions of CB and UMI. The software will analyze directly and automatically identify these positions. However, if there are multiple sequences with inconsistent lengths, manual trimming is required.

**Comment by Tc940417** [comment]
thanks for your answer @lishuangshuang0616
