### ISSUE TITLE
 Command failed with exit code 255

### ISSUE THREAD

**Issue by Arknights2** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#77]
Dear Professor

I encountered such an error when using dnbctools to process the offline data

**scATAC data were analyzed, and the script followed the github prompts strictly**

dnbc4tools atac run \

--fastq1 Sample1_1.fq.gz,Sample2_1.fq.gz \

--fastq2 Sample1_2.fq.gz,Sample2_2.fq.gz \

--genomeDir /human_hg38  \

--name DIPSEQT1 --threads 20

There are no problems in the other several samples for the time being. I sincerely ask how you can solve this error

**Comment by lishuangshuang0616** [comment]
Please capture the full error message. I need it for reference.

**Comment by Arknights2** [comment]
Sorry for not showing more information about this error

I added this part of the main information in the link



**Log file**:

2024-06-04 12:49:23, 475-data-ERROR-Command failed with exit code 255

2024-06-04 12:49:23, 476-data-ERROR -

 **alignment.report.tsv**:

Didn't reach the end of sequence file, which might be corrupted!

[error.txt](https://github.com/user-attachments/files/15544306/error.txt)


Terminates in the process of generating the 01.data file

**Comment by lishuangshuang0616** [comment]
Chromap reported an error when aligning. Can you take a screenshot of the 01.data directory? I might suggest you rerun the command analysis.

**Comment by Arknights2** [comment]
Thank you for your reply

I have repeated the calculation three times with the same error

I didn't have this problem when I was dealing with other files, only this sample had a problem, which made me very confused
<img width="440" alt="filelist" src="https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/149868330/8f5d33cb-8a55-4de7-8c41-f6853b7bbb9a">

**Comment by Arknights2** [comment]
Thank you for your reply

I have repeated the calculation three times with the same error

I didn't have this problem when I was dealing with other files, only this sample had a problem, which made me very confused
<img width="284" alt="01data_file_list" src="https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/149868330/1522c3b1-e55a-440a-a6ff-7cc4b4fd4777">

**Comment by lishuangshuang0616** [comment]
This is the first time I have seen this error. I want to see the information in the alignment.report.tsv file.
```
--fastq1 Sample1_1.fq.gz,Sample2_1.fq.gz \
--fastq2 Sample1_2.fq.gz,Sample2_2.fq.gz \
```
Is the datas one sample? sample1?sample2?

**Comment by Arknights2** [comment]
Thank you for your reply

I have just re-checked the files and the data are samples from the same person

For privacy purposes, I have hidden the path of some files

The alignment.report.tsv file is shown to you as a screenshot

Most of the content is repetitive, such as: "Loaded sequence batch successfully in 0.41s, number of sequences: 500000." and "Mapped 500000 read pairs in 3.99s."
<img width="1121" alt="log1" src="https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/149868330/ac9669f8-7517-43d0-93d6-54e8b3cb2336">
<img width="495" alt="log2" src="https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/149868330/8eb6aa60-a4d6-4e29-8de8-7277b3e6545c">
<img width="496" alt="log3" src="https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/149868330/7f66b297-8341-46fb-962b-b248fd8c9f7b">

**Comment by lishuangshuang0616** [comment]
https://github.com/haowenz/chromap/issues/134
refer to this,  check the integrity of the input fastq files.

**Comment by Arknights2** [comment]
Thank you for your help, I will go to test as soon as possible！

**Comment by Arknights2** [comment]
Thank you very much for your help!
I have found the problem and it was indeed due to incomplete fastq files.
