### ISSUE TITLE
输出结果中怎么能包含那些没有gene名字只有geneID的reads counts

### ISSUE THREAD

**Issue by JiangLab-st** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#8]
在输出结果中只有具有基因名字的结果，能否让输出文件中在没有gene名字的情况下输出对应的gene ID并给出对应的read counts数
一些基因在gtf文件中只包含了geneID但是没有gene name，我们怎么设置就可以输出所有有基因ID的结果

**Comment by lishuangshuang0616** [comment]
在版本2.0.0中无法对只包含gene_id而没有gene_name的gene进行注释，但是在版本2.0.5中我们进行了改变，可以更新流程重新进行分析
