### ISSUE TITLE
dnbc4tools rna run 的时候报错：Signals.SIGABRT: 6

### ISSUE THREAD

**Issue by YaoQiong1127** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#83]
您好，我在使用 dnbc4tools rna run 的时候，出现报错，信息如下：

代码：
export LD_LIBRARY_PATH=/HXsz1/YQ/Software/Miniconda3/envs/dnbc4tools-2.1.2/lib:/HXsz1/YQ/Software/Miniconda3/lib:/usr/lib64:/usr/lib
binscr=/HXsz1/YQ/Software/Miniconda3/envs/dnbc4tools-2.1.2/bin/dnbc4tools
db_dir=/HXsz1/YQ/Software/Miniconda3/envs/dnbc4tools-2.1.2/database/Mouse-GRCm38
Sample=KO_5
cDNAfq1=/HXsz1/YQ/Project/scRNA-Seq.C4/testing/Raw_Data/E250013997_L01_KO_5_1.fq.gz
cDNAfq2=/HXsz1/YQ/Project/scRNA-Seq.C4/testing/Raw_Data/E250013997_L01_KO_5_2.fq.gz
Oligofq1=/HXsz1/YQ/Project/scRNA-Seq.C4/testing/Raw_Data/E250015259_L01_KO_5_oligo_1.fq.gz
Oligofq2=/HXsz1/YQ/Project/scRNA-Seq.C4/testing/Raw_Data/E250015259_L01_KO_5_oligo_2.fq.gz
$binscr rna run --name $Sample --cDNAfastq1 $cDNAfq1 --cDNAfastq2 $cDNAfq2 --oligofastq1 $Oligofq1 --oligofastq2 $Oligofq2 --genomeDir $db_dir --threads 8 --calling_method "emptydrops" --expectcells 5000

报错信息：
Chemistry(darkreaction) determined in oligoR1 : v2v3nodarkreaction
Chemistry(darkreaction) determined in oligoR2 : nodarkreaction
Chemistry(darkreaction) determined in cDNAR1 : scRNAv2v3HT

2024-06-25 11:19:35
Conduct quality control for cDNA library barcoding, perform alignment.

2024-06-25 11:19:35
Perform quality control for oligo library barcodes.

Traceback (most recent call last):
  File "/HXsz1/YQ/Software/Miniconda3/envs/dnbc4tools-2.1.2/bin/dnbc4tools", line 8, in <module>
    sys.exit(main())
  File "/HXsz1/YQ/Software/Miniconda3/envs/dnbc4tools-2.1.2/lib/python3.8/site-packages/dnbc4tools/dnbc4tools.py", line 110, in main
    args.func(args)
  File "/HXsz1/YQ/Software/Miniconda3/envs/dnbc4tools-2.1.2/lib/python3.8/site-packages/dnbc4tools/rna/run.py", line 144, in run
    Runpipe(args).runpipe()
  File "/HXsz1/YQ/Software/Miniconda3/envs/dnbc4tools-2.1.2/lib/python3.8/site-packages/dnbc4tools/rna/run.py", line 131, in runpipe
    start_print_cmd(pipecmd,os.path.join(self.outdir,self.name))
  File "/HXsz1/YQ/Software/Miniconda3/envs/dnbc4tools-2.1.2/lib/python3.8/site-packages/dnbc4tools/tools/utils.py", line 138, in start_print_cmd
    subprocess.check_call(arg, shell=True)
  File "/HXsz1/YQ/Software/Miniconda3/envs/dnbc4tools-2.1.2/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/HXsz1/YQ/Software/Miniconda3/envs/dnbc4tools-2.1.2/bin/dnbc4tools rna data --cDNAfastq1 /HXsz1/YQ/Project/scRNA-Seq.C4/testing/Raw_Data/E250013997_L01_KO_5_1.fq.gz --cDNAfastq2 /HXsz1/YQ/Project/scRNA-Seq.C4/testing/Raw_Data/E250013997_L01_KO_5_2.fq.gz --oligofastq1 /HXsz1/YQ/Project/scRNA-Seq.C4/testing/Raw_Data/E250015259_L01_KO_5_oligo_1.fq.gz --oligofastq2 /HXsz1/YQ/Project/scRNA-Seq.C4/testing/Raw_Data/E250015259_L01_KO_5_oligo_2.fq.gz --threads 8 --name KO_5 --chemistry auto --darkreaction auto --outdir /HXsz1/YQ/Project/scRNA-Seq.C4/testing/ztmp_KO_5 --genomeDir /HXsz1/YQ/Software/Miniconda3/envs/dnbc4tools-2.1.2/database/Mouse-GRCm38 --gtf /HXsz1/YQ/Software/Miniconda3/envs/dnbc4tools-2.1.2/database/Mouse-GRCm38/genes.filter.gtf --chrMT chrM' died with <Signals.SIGABRT: 6>.

已输出数据：
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/169013332/e5c98d11-b8b8-4816-b760-ee1dbf7698f9)

数据库目录：
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/169013332/d96b1003-ff4a-4996-913a-d541c9afe3c1)
数据库生成过程无异常信息；

能麻烦您帮忙看一下报错的原因吗？

**Comment by lishuangshuang0616** [comment]
After looking at your directory, your alignment process has generated **6.2G** of **_Aligned.out.bam_**, which means that there is no problem at the beginning of the alignment process. However, during the operation, the node memory was occupied at a certain time period, resulting in insufficient running memory. You can confirm whether this problem exists. Re-analyze to ensure that the memory is stable.

**Comment by lishuangshuang0616** [comment]
Sorry, I just checked carefully and your comparison has finished running and generated **_Log.final.out_**.

**Comment by YaoQiong1127** [comment]
是的，比对看上去已经跑完了；Log.out 的倒数第2、3两行，显示 “finished building index!”：
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/169013332/4980236d-3c0b-4c4f-a6c0-453808eb1bb4)
但 01.data 里面，并没有 bam的index文件；

**Comment by lishuangshuang0616** [comment]
```
export PATH=/haplox/users/yaoqiong/Software/Miniconda3/envs/dnbc4tools-2.1.2/bin:$PATH
export LD_LIBRARY_PATH=/haplox/users/yaoqiong/Software/Miniconda3/envs/dnbc4tools-2.1.2/lib:$LD_LIBRARY_PATH
/haplox/users/yaoqiong/Software/Miniconda3/envs/dnbc4tools-2.1.2/lib/python3.8/site-packages/dnbc4tools/software/Anno -I /haplox/users/yaoqiong/Project/scRNA-Seq.C4/testing/ztmp_KO_5/01.data/Aligned.out.bam -a /haplox/users/yaoqiong/Software/Miniconda3/envs/dnbc4tools-2.1.2/database/Mouse-GRCm38/genes.filter.gtf -L /haplox/users/yaoqiong/Project/scRNA-Seq.C4/testing/ztmp_KO_5/01.data/cDNA.barcode.counts.txt -o /haplox/users/yaoqiong/Project/scRNA-Seq.C4/testing/ztmp_KO_5/01.data -c 10 -m chrM -B /haplox/users/yaoqiong/Software/Miniconda3/envs/dnbc4tools-2.1.2/lib/python3.8/site-packages/dnbc4tools/config/cellbarcode/scRNAv2v3HT/scRNA_beads_v2_3.json --anno 1 --intron
```

Please test this command manually. I want to see what went wrong with **_Anno_**.

**Comment by lishuangshuang0616** [comment]
[libgcc_s.so.1 must be installed for pthread_cancel to work](https://stackoverflow.com/questions/64797838/libgcc-s-so-1-must-be-installed-for-pthread-cancel-to-work)

I have not encountered this error. Try adding
```
import ctypes
libgcc_s = ctypes.CDLL('libgcc_s.so.1')
```
to the top line of _/haplox/users/yaoqiong/Software/Miniconda3/envs/dnbc4tools-2.1.2/lib/python3.8/site-packages/dnbc4tools/rna/data.py_

**Comment by YaoQiong1127** [comment]
> ```
> export PATH=/haplox/users/yaoqiong/Software/Miniconda3/envs/dnbc4tools-2.1.2/bin:$PATH
> export LD_LIBRARY_PATH=/haplox/users/yaoqiong/Software/Miniconda3/envs/dnbc4tools-2.1.2/lib:$LD_LIBRARY_PATH
> /haplox/users/yaoqiong/Software/Miniconda3/envs/dnbc4tools-2.1.2/lib/python3.8/site-packages/dnbc4tools/software/Anno -I /haplox/users/yaoqiong/Project/scRNA-Seq.C4/testing/ztmp_KO_5/01.data/Aligned.out.bam -a /haplox/users/yaoqiong/Software/Miniconda3/envs/dnbc4tools-2.1.2/database/Mouse-GRCm38/genes.filter.gtf -L /haplox/users/yaoqiong/Project/scRNA-Seq.C4/testing/ztmp_KO_5/01.data/cDNA.barcode.counts.txt -o /haplox/users/yaoqiong/Project/scRNA-Seq.C4/testing/ztmp_KO_5/01.data -c 10 -m chrM -B /haplox/users/yaoqiong/Software/Miniconda3/envs/dnbc4tools-2.1.2/lib/python3.8/site-packages/dnbc4tools/config/cellbarcode/scRNAv2v3HT/scRNA_beads_v2_3.json --anno 1 --intron
> ```
> 
> Please test this command manually. I want to see what went wrong with **_Anno_**.

![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/169013332/cebd33ca-d731-480d-8c99-83567d6f0930)

![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/169013332/79c19410-4e7c-4e99-b73e-580bcbc6c71c)

单独跑 Anno，无报错，final.bam, anno_report.csv, alignment_report.csv, beads_stat.txt 这4个文件可以正常生成；

![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/169013332/6df6959a-4abb-47a7-8b84-11762be24dae)

**Comment by YaoQiong1127** [comment]
> [libgcc_s.so.1 must be installed for pthread_cancel to work](https://stackoverflow.com/questions/64797838/libgcc-s-so-1-must-be-installed-for-pthread-cancel-to-work)
> 
> I have not encountered this error. Try adding
> 
> ```
> import ctypes
> libgcc_s = ctypes.CDLL('libgcc_s.so.1')
> ```
> 
> to the top line of _/haplox/users/yaoqiong/Software/Miniconda3/envs/dnbc4tools-2.1.2/lib/python3.8/site-packages/dnbc4tools/rna/data.py_

好的，我试试

**Comment by YaoQiong1127** [comment]
> [libgcc_s.so.1 must be installed for pthread_cancel to work](https://stackoverflow.com/questions/64797838/libgcc-s-so-1-must-be-installed-for-pthread-cancel-to-work)
> 
> I have not encountered this error. Try adding
> 
> ```
> import ctypes
> libgcc_s = ctypes.CDLL('libgcc_s.so.1')
> ```
> 
> to the top line of _/haplox/users/yaoqiong/Software/Miniconda3/envs/dnbc4tools-2.1.2/lib/python3.8/site-packages/dnbc4tools/rna/data.py_

这样处理之后，之前报错的步骤已正常运行了，但出现了新的报错：

![ztmp_p1](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/169013332/86a746bd-a64a-4b3c-bc08-90856e5bb843)

![ztmp_p2](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/169013332/651758ce-9cc8-4c09-a842-249480c31901)

![ztmp_p3](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/169013332/40418d5a-ba9c-4c4d-aaa3-1a5afd389295)

![ztmp_p4](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/169013332/e38d8440-1a50-43d8-9997-0f5c90eb4299)

**Comment by lishuangshuang0616** [comment]
实在很抱歉给你带来这么不好的体验。
从报错结果来看处理oligo数据时报错。我重新注释了前面的步骤然后直接运行该步骤进行测试。
使用我提供的这个文件[data.py](https://raw.githubusercontent.com/lishuangshuang0616/some/main/data.py)替换下 _/haplox/users/yaoqiong/Software/Miniconda3/envs/dnbc4tools-2.1.2/lib/python3.8/site-packages/dnbc4tools/rna/data.py_ 这个文件，原data.py文件记得备份。
测试时如果还是出现这个报错，将 _**oligo_combine_pl**_ 改成 _**oligo_combine_pd**_ 再次进行尝试。
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/49019821/48e610cf-5404-45c1-8f7e-1ec841706771)
最终看测试结果再决定如何调整代码。
麻烦了。

**Comment by YaoQiong1127** [comment]
> 实在很抱歉给你带来这么不好的体验。 从报错结果来看处理oligo数据时报错。我重新注释了前面的步骤然后直接运行该步骤进行测试。 使用我提供的这个文件[data.py](https://raw.githubusercontent.com/lishuangshuang0616/some/main/data.py)替换下 _/haplox/users/yaoqiong/Software/Miniconda3/envs/dnbc4tools-2.1.2/lib/python3.8/site-packages/dnbc4tools/rna/data.py_ 这个文件，原data.py文件记得备份。 测试时如果还是出现这个报错，将 _**oligo_combine_pl**_ 改成 _**oligo_combine_pd**_ 再次进行尝试。 ![image](https://private-user-images.githubusercontent.com/49019821/342795199-48e610cf-5404-45c1-8f7e-1ec841706771.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNjQzMjQsIm5iZiI6MTcxOTM2NDAyNCwicGF0aCI6Ii80OTAxOTgyMS8zNDI3OTUxOTktNDhlNjEwY2YtNTQwNC00NWMxLThmN2UtMWVjODQxNzA2NzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDAxMDcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmMGNhMDQ1OTkyYTcyNjFhMGNjNTE5ZWFiYmNjZWI1ZTY2NGZiNjM3YWVhNTA3Njk0YzIyNDc1ZDc3ZDhjZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L12Fje8lxSxeMuvKhBT3r7SFj0acSwE9gjil677HreA) 最终看测试结果再决定如何调整代码。 麻烦了。

替换 data.py 之后，没有运行，直接报错了：

![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/169013332/96c69dad-b240-4fc3-af6e-aea91b80101a)

**Comment by lishuangshuang0616** [comment]
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/49019821/e0db9485-83c7-4269-9f74-2c48f813c2ad)
先注释了试试.

**Comment by YaoQiong1127** [comment]
> ![image](https://private-user-images.githubusercontent.com/49019821/342990876-e0db9485-83c7-4269-9f74-2c48f813c2ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNzI5NDUsIm5iZiI6MTcxOTM3MjY0NSwicGF0aCI6Ii80OTAxOTgyMS8zNDI5OTA4NzYtZTBkYjk0ODUtODNjNy00MjY5LTlmNzQtMmM0OGY4MTNjMmFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDAzMzA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxODJjOGNmNmMzNzA1NjI3ZDBkNjRkYjc3YzEyODQ3ODZlMDk5ZWJmNzNmMmM1MWYwMmU2N2ZhOTU3YjAzNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iKywjbAEsmCml0I7Glp_oS5RNe94brVQzf50uE9zLm8) 先注释了试试.

不运行，直接报错了：

![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/169013332/2b1c4117-e840-4167-8fae-7d6c2534f448)

**Comment by lishuangshuang0616** [comment]
你是重新开了个新的分析吗,在原分析目录运行即可,我看你的oligo.reads.fq.gz找不到了

**Comment by YaoQiong1127** [comment]
> 你是重新开了个新的分析吗,在原分析目录运行即可,我看你的oligo.reads.fq.gz找不到了

啊，是的；我再试试

**Comment by YaoQiong1127** [comment]
> ![image](https://private-user-images.githubusercontent.com/49019821/342990876-e0db9485-83c7-4269-9f74-2c48f813c2ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTM2NjYsIm5iZiI6MTcxOTM5MzM2NiwicGF0aCI6Ii80OTAxOTgyMS8zNDI5OTA4NzYtZTBkYjk0ODUtODNjNy00MjY5LTlmNzQtMmM0OGY4MTNjMmFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA5MTYwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhYTU0MTI0ZmM2YjZlNTVlYWQwNWZlMzUxZjk3MTk2YmEzNjQ5Zjk3M2VhNGI4ZjU0NTY1NzM4YWU3ZTAxY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ckQV2QH66kicRYN7ZhxIjUEpSmoDSEfIVZf-jA1ryQw) 先注释了试试.

我用了您新发给我的 data.py , oligo_combine_pl 和 oligo_combine_pd 都试过，但都报错了：

![zzz_p2](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/169013332/5fe9cb09-d76a-43ce-828f-fa23ccbd0d02)

![zzz_p1](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/169013332/a2ce60f2-a81c-4c4c-aaf4-7bea2b0a7e6f)

**Comment by lishuangshuang0616** [comment]
分析的时候这个报错一般都是内存问题。能注意到内存占用吗？很奇怪，pd的话应该不会导致大内存。

**Comment by YaoQiong1127** [comment]
> 分析的时候这个报错一般都是内存问题。能注意到内存占用吗？很奇怪，pd的话应该不会导致大内存。

内存占用不是太高：

![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/169013332/fe99d345-b054-43fb-add5-4b5a7827e3d2)

![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/169013332/f6d6b33d-b44a-469e-b14b-89871cbfbfd9)

**Comment by lishuangshuang0616** [comment]
Check if **_export LD_LIBRARY_PATH_** exists in your **_bashrc_**. If it does, comment it out and open a new terminal before re-running the  work. The software will use Python multi threading in several places, so addressing the environment is necessary.
