### ISSUE TITLE
我该如何将结果文件读取到 python 中进行后续分析（包括 UMAP 和细胞类型注释）？（Scanpy）

### ISSUE THREAD

**Issue by zhoutianrui-tongji** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#89]
我已经完整的运行完了单细胞的流程，并得到了正确的结果文件。
这是我的目录结构：
<img width="240" alt="image" src="https://github.com/user-attachments/assets/6fc82755-4046-44a3-a0ee-dc892f482133">

然后我使用了如下的 python 代码：
import scanpy as sc
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 加载数据
resdir = "./hiPS-CM-D3/"
h5ad_file = f'{resdir}output/filter_feature.h5ad'
adata = sc.read_h5ad(h5ad_file)
adata

cluster = pd.read_csv(f'{resdir}03.analysis/cluster.csv')
markers = pd.read_csv(f'{resdir}03.analysis/marker.csv')

# 确保细胞ID匹配
cluster.set_index('Unnamed: 0', inplace=True)

adata = adata[adata.obs_names.isin(cluster.index)]

# 添加UMAP坐标到adata
adata.obsm['X_umap'] = cluster[['UMAP_1', 'UMAP_2']].values

# 将cluster数据集中的其他相关信息添加到adata.obs中
adata.obs['nGene'] = cluster['nGene']
adata.obs['nUMI'] = cluster['nUMI']

adata.obs['leiden'] = cluster['leiden']

adata.obs['Cluster'] = cluster['Cluster']
adata.obs['Cluster'] = adata.obs['Cluster'].astype('category')

adata.obs['Predict_number'] = cluster['Predict_number']
adata.obs['Predicted_cell_type'] = cluster['Predicted cell type']
adata.obs['Predicted_cell_type'] = adata.obs['Predicted_cell_type'].astype('category')

# 验证数据整合结果
print(adata.obs.head())

# 绘制UMAP图，按Cluster聚类着色
sc.pl.umap(adata, color='Cluster',  palette='tab20')

# 可视化预测的细胞类型，按类别着色，并增加图例
sc.pl.umap(adata, color='Predicted_cell_type', palette='tab20')
得到了如下的结果：
<img width="971" alt="image" src="https://github.com/user-attachments/assets/404120cb-e762-431b-874c-7ab286a8e4cc">

但是这与网页的结果相差很大，我不知道发生了什么？
网页的结果如下：
<img width="621" alt="image" src="https://github.com/user-attachments/assets/58e246fe-4931-4d90-ab69-aa25af4680d9">
<img width="880" alt="image" src="https://github.com/user-attachments/assets/a08920b6-2a6b-4842-bd34-824c192cee5f">

期待您的解答！谢谢

**Comment by lishuangshuang0616** [comment]
![image](https://github.com/user-attachments/assets/cc11813f-ebba-43d2-bce2-496b5c06b029)
![image](https://github.com/user-attachments/assets/e4af9487-0227-4346-878e-70ef9fa2fc99)

You can see that the cell ordering in adata and the cell ordering in cluster are not consistent. You need to adjust the cluster according to the order of adata.obs.

```
cluster.set_index('Unnamed: 0', inplace=True)
adata = adata[adata.obs_names.isin(cluster.index)]

# sort cluster index
reindexed_cluster = cluster.reindex(adata.obs.index) 
adata.obsm['X_umap'] = reindexed_cluster[['UMAP_1', 'UMAP_2']].values
```

**Comment by zhoutianrui-tongji** [comment]
It worked, thank you very much！：）
