### ISSUE TITLE
输出features文件

### ISSUE THREAD

**Issue by HengkuanLi** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#9]
输出结果中，features文件中只能有一列吗，可以输出第一列为基因ENSEMBL ID，第二列为基因symbol呢？

**Comment by lishuangshuang0616** [comment]
目前暂时没有实现，下游分析可参考https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/blob/version2.0/doc/Downstream_Analysis.md
