### ISSUE TITLE
dnbc4tools run 报错 Error code: SAW-A10187

### ISSUE THREAD

**Issue by sheny-bio** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#92]
Chemistry(darkreaction) determined in oligoR1 : v2v3nodarkreaction
Chemistry(darkreaction) determined in oligoR2 : nodarkreaction
Chemistry(darkreaction) determined in cDNAR1 : scRNAv2v3HT

2024-08-06 17:47:02
Conduct quality control for cDNA library barcoding, perform alignment.

2024-08-06 17:47:02
Perform quality control for oligo library barcodes.
2024-08-06 17:48:06,961 - data - ERROR - Command failed with exit code 1
2024-08-06 17:48:06,975 - data - ERROR - 2024-8-6  17:47:3 ..... started STAR run
Aug 06 17:47:03 ..... loading genome
Aug 06 17:47:53 ..... started mapping
Error code: SAW-A10187
Error,read name format error:

这是错误日志，这个报错的原因是什么呢

**Comment by sheny-bio** [comment]
libhts.so.3: cannot open shared object file: No such file or directory 应该是这个问题

**Comment by sheny-bio** [comment]
Error code: SAW-A10187
Error,read name format error:  这个错误是什么意思呀

**Comment by lishuangshuang0616** [comment]
read name error, could you please screenshot to check if the read names in your FASTQ R1 and R2 files are formatted correctly?

**Comment by lishuangshuang0616** [comment]
> libhts.so.3: cannot open shared object file: No such file or directory 应该是这个问题

it's not same error
this issue is cause libhts not install correctly.
```
conda install -c conda-forge -c bioconda htslib=1.18 samtools=1.18
```

**Comment by sheny-bio** [comment]
> read name error, could you please screenshot to check if the read names in your FASTQ R1 and R2 files are formatted correctly?读取名称错误，您能否截图检查一下您的 FASTQ R1 和 R2 文件中的读取名称格式是否正确？

![image](https://github.com/user-attachments/assets/82b7a17c-6695-4826-93da-c23e9426e667)
![image](https://github.com/user-attachments/assets/7064e7d5-e178-486d-8349-a05cbf1d7b9a)
![image](https://github.com/user-attachments/assets/bb140b15-b49e-4a2a-8ab3-f6f0f0b26c1b)
![image](https://github.com/user-attachments/assets/77d09c78-72aa-4e23-a704-78ac9ea27ada)
这是cDNA和oligo文件。read name我们应该确实做了一些处理。是不符合规范吗

**Comment by lishuangshuang0616** [comment]
Yes, the software encounters errors when there are spaces or tag information present after the "/1" or "/2" in the read names. 
It is recommended to use the original format without such additions.

**Comment by sheny-bio** [comment]
问题已经解决啦，用下机原始的fq文件就可以。谢谢~

**Comment by sw1125598670** [comment]
我也有这个问题，请问一下原始的fq格式是什么样的
