### ISSUE TITLE
来自不同分析版本的样品

### ISSUE THREAD

**Issue by LJIGDBLL** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#98]
开发者您好，我想请问一下，华大单细胞上游软件版本更新了多代，不同版本产出的细胞和基因信息有所差别。不同版本间的样本是否可以在下游分析时放一块分析，一起做integrated UMAP。还是说必须统一在同一个版本的dnbelabtools下运行。先前做的样本都是用老版本跑的~

**Comment by lishuangshuang0616** [comment]
如果是软件V2.0之后的版本可以不用重新分析。整体的比对注释cell calling逻辑变化不会很大。

**Comment by LJIGDBLL** [comment]
好的，谢谢您的回答！
